import { useEffect, useMemo, useState } from 'react'
import type { FinalActionConfig, GitLabMrActionConfig, PatchActionConfig, PreflightResult, ProjectConfig, RoutingOperator, SettingsResponse, VerificationStepConfig } from '../entities/config'
import { ApiError, api } from '../lib/api'

const emptyProject = (): ProjectConfig => ({
  id: '', name: '', enabled: true,
  routingRules: [{ id: 'primary-route', providerRef: '', priority: 100, catchAll: true, conditions: [] }],
  modificationSource: { id: 'project-source', type: 'git', repositoryRef: '', executableRef: 'git-cli', allowedRoots: ['.'], deniedRoots: [], allowedExtensions: [] },
  agents: { discovery: '', repair: '', review: '' },
  verification: { timeoutSeconds: 1200, steps: [], allowNoAutomatedTests: false, reason: '' },
  finalActions: [{ id: 'primary-patch', type: 'patch', outputDirectoryRef: 'primary-patches', filenameTemplate: '{task_id}-{run_id}.patch', overwrite: false }],
})
const csv=(value:string)=>value.split(',').map(item=>item.trim()).filter(Boolean)
const firstRule=(project:ProjectConfig)=>project.routingRules?.[0]??{id:'primary-route',providerRef:'',priority:100,catchAll:true,conditions:[]}
const patchAction=(action:FinalActionConfig|undefined):PatchActionConfig=>action?.type==='patch'?action:{id:'primary-patch',type:'patch',outputDirectoryRef:'primary-patches',filenameTemplate:'{task_id}-{run_id}.patch',overwrite:false}
const mrAction=(action:FinalActionConfig|undefined):GitLabMrActionConfig=>action?.type==='gitlabMr'?action:{id:'main-gitlab-mr',type:'gitlabMr',connectionRef:'',projectPath:'',materializationRepositoryRef:'git-materialization',gitExecutableRef:'git-cli',targetBranches:['main'],pathMappings:[{from:'.',to:'.'}],titleTemplate:'[CodeFixer] {task_id}',descriptionTemplate:'Automated repair from CodeFixer run {run_id}.'}

export function ProjectsPage() {
  const [projects,setProjects]=useState<ProjectConfig[]>([]);const [settings,setSettings]=useState<SettingsResponse|null>(null);const [editor,setEditor]=useState<ProjectConfig|null>(null);const [preflights,setPreflights]=useState<Record<string,PreflightResult>>({});const [error,setError]=useState('');const [busy,setBusy]=useState(false)
  const reload=async()=>{const[p,s]=await Promise.all([api.projects(),api.settings()]);setProjects(p.items);setSettings(s)}
  useEffect(()=>{reload().catch(e=>setError(e instanceof Error?e.message:'加载失败'))},[])
  const profileIds=useMemo(()=>settings?.config.agentProfiles.map(p=>p.id).filter(Boolean)??[],[settings]);const providerIds=useMemo(()=>settings?.config.ticketProviders.map(p=>p.id).filter(Boolean)??[],[settings]);const connectionIds=useMemo(()=>settings?.config.connections.map(p=>p.id).filter(Boolean)??[],[settings]);const pathIds=useMemo(()=>Object.keys(settings?.config.pathBindings??{}),[settings]);const executableIds=useMemo(()=>Object.keys(settings?.config.executableBindings??{}),[settings])
  const updateRule=(patch:Partial<NonNullable<ProjectConfig['routingRules']>[number]>)=>{if(!editor)return;setEditor({...editor,routingRules:[{...firstRule(editor),...patch}]})};const updateSource=(patch:Partial<NonNullable<ProjectConfig['modificationSource']>>)=>editor&&setEditor({...editor,modificationSource:{...editor.modificationSource,...patch}});const setAction=(action:FinalActionConfig)=>editor&&setEditor({...editor,finalActions:[action]})
  const save=async()=>{if(!editor||!settings)return;setBusy(true);setError('');try{const result=await api.createProject(editor,settings.etag);setSettings({...settings,etag:result.etag});setEditor(null);await reload()}catch(e){setError(e instanceof ApiError?e.message:'保存失败')}finally{setBusy(false)}}
  const preflight=async(id:string)=>{setBusy(true);try{const result=await api.preflight(id);setPreflights(v=>({...v,[id]:result}))}catch(e){setError(e instanceof Error?e.message:'Preflight 失败')}finally{setBusy(false)}}
  const addVerification=()=>{if(!editor)return;const steps=editor.verification?.steps??[];const step:VerificationStepConfig={id:`step-${steps.length+1}`,executableRef:'',args:[],workingDirectory:'.',required:true};setEditor({...editor,verification:{...editor.verification,steps:[...steps,step]}})}
  const updateVerification=(index:number,patch:Partial<VerificationStepConfig>)=>{if(!editor)return;const steps=[...(editor.verification?.steps??[])];steps[index]={...steps[index],...patch};setEditor({...editor,verification:{...editor.verification,steps}})}
  const currentAction=editor?.finalActions?.[0];const currentPatch=patchAction(currentAction);const currentMr=mrAction(currentAction);const route=editor?firstRule(editor):null;const routeCondition=route?.conditions?.[0]
  return <section className="page-stack"><div className="page-heading"><div><span className="eyebrow">PROJECT POLICY</span><h1>项目</h1><p>一条项目策略 = 唯一路由 + 唯一修改源 + 三个 Agent 角色 + 验证 + 必需交付动作。</p></div><button className="primary compact" onClick={()=>setEditor(emptyProject())}>＋ 新建项目</button></div>{error&&<button className="notice-strip error-note" onClick={()=>setError('')}>{error}</button>}
  {projects.length===0?<div className="empty-state"><span className="empty-mark">◇</span><h2>还没有项目</h2><p>先建立一个完整可执行策略。CodeFixer 不会在没有唯一项目路由时猜修改源。</p><button className="primary compact" onClick={()=>setEditor(emptyProject())}>创建第一个项目</button></div>:<div className="project-grid">{projects.map(project=>{const pf=preflights[project.id];const rule=project.routingRules?.[0];return <article className="project-card" key={project.id}><div className="project-card-head"><div><span className="ticket">{project.id}</span><h3>{project.name||project.id}</h3></div><span className={`readiness-badge ${pf?.ready?'ready':pf?'failed':'unknown'}`}>{pf?.ready?'READY':pf?'NOT READY':'UNCHECKED'}</span></div><div className="route-signature"><span>{rule?.providerRef||'NO ROUTE'}</span><i>→</i><b>{project.modificationSource?.type?.toUpperCase()||'—'} · {project.modificationSource?.repositoryRef||'未绑定'}</b></div><div className="project-spec"><div><small>Agent Chain</small><b>{project.agents?.discovery||'—'} → {project.agents?.repair||'—'} → {project.agents?.review||'—'}</b></div><div><small>最终动作</small><b>{project.finalActions?.map(a=>a.type).join(' + ')||'未配置'}</b></div></div>{pf&&<div className="preflight-mini">{pf.checks.slice(0,8).map(c=><div key={c.id} className={c.status}><i/>{c.summary}</div>)}</div>}<button className="ghost action-link" disabled={busy} onClick={()=>void preflight(project.id)}>运行 Preflight →</button></article>})}</div>}
  {editor&&settings&&route&&<div className="modal-backdrop editor-backdrop"><div className="config-modal project-editor" role="dialog" aria-modal="true" aria-labelledby="project-editor-title"><div className="modal-head"><div><span className="signal-kicker">PROJECT BLUEPRINT</span><h2 id="project-editor-title">建立可执行项目</h2><p>保存前先把路由、代码源、Agent、验证和交付收敛成一条闭环。</p></div><button className="icon-btn" onClick={()=>setEditor(null)} aria-label="关闭">×</button></div>
  <div className="editor-section"><div className="editor-section-title"><span>01</span><div><b>项目身份与路由</b><small>外部 Bug 必须确定性地只命中一个项目</small></div></div><div className="form-grid"><label>项目 ID<input value={editor.id} onChange={e=>setEditor({...editor,id:e.target.value})} placeholder="product-lua"/></label><label>显示名称<input value={editor.name??''} onChange={e=>setEditor({...editor,name:e.target.value})} placeholder="Product / Lua"/></label><label>Provider<select value={route.providerRef} onChange={e=>updateRule({providerRef:e.target.value})}><option value="">选择工单来源</option>{providerIds.map(id=><option key={id}>{id}</option>)}</select></label><label>优先级<input type="number" value={route.priority} onChange={e=>updateRule({priority:Number(e.target.value)||0})}/></label></div><label className="check-row"><input type="checkbox" checked={!!route.catchAll} onChange={e=>updateRule({catchAll:e.target.checked,conditions:e.target.checked?[]:[{field:'module',operator:'contains',value:''}]})}/><span>这个 Provider 的工单全部路由到本项目（Catch All）</span></label>{!route.catchAll&&<div className="route-condition"><label>工单字段<input value={String(routeCondition?.field??'module')} onChange={e=>updateRule({conditions:[{field:e.target.value,operator:(routeCondition?.operator??'contains') as RoutingOperator,value:routeCondition?.value??''}]})} placeholder="module / project.id / raw.xxx"/></label><label>条件<select value={routeCondition?.operator??'contains'} onChange={e=>updateRule({conditions:[{field:routeCondition?.field??'module',operator:e.target.value as RoutingOperator,value:routeCondition?.value??''}]})}><option value="contains">包含</option><option value="eq">等于</option><option value="neq">不等于</option><option value="exists">存在</option></select></label><label>值<input disabled={routeCondition?.operator==='exists'} value={String(routeCondition?.value??'')} onChange={e=>updateRule({conditions:[{field:routeCondition?.field??'module',operator:(routeCondition?.operator??'contains') as RoutingOperator,value:e.target.value}]})}/></label></div>}</div>
  <div className="editor-section"><div className="editor-section-title"><span>02</span><div><b>唯一修改源</b><small>Agent 只能在这一份隔离代码空间内工作</small></div></div><div className="form-grid"><label>类型<select value={editor.modificationSource?.type} onChange={e=>updateSource({type:e.target.value as 'git'|'svn',executableRef:e.target.value==='git'?'git-cli':'svn-cli'})}><option value="git">Git</option><option value="svn">SVN</option></select></label><label>Repository Ref<select value={editor.modificationSource?.repositoryRef??''} onChange={e=>updateSource({repositoryRef:e.target.value})}><option value="">选择 pathBinding</option>{pathIds.map(id=><option key={id}>{id}</option>)}</select></label><label>CLI Ref<select value={editor.modificationSource?.executableRef??''} onChange={e=>updateSource({executableRef:e.target.value})}>{executableIds.map(id=><option key={id}>{id}</option>)}</select></label><label>允许扩展名<input value={(editor.modificationSource?.allowedExtensions??[]).join(', ')} onChange={e=>updateSource({allowedExtensions:csv(e.target.value)})} placeholder=".py, .ts, .lua；留空=不限"/></label><label>允许根目录<input value={(editor.modificationSource?.allowedRoots??['.']).join(', ')} onChange={e=>updateSource({allowedRoots:csv(e.target.value)})} placeholder="src, scripts"/></label><label>禁止根目录<input value={(editor.modificationSource?.deniedRoots??[]).join(', ')} onChange={e=>updateSource({deniedRoots:csv(e.target.value)})} placeholder="vendor, generated"/></label></div></div>
  <div className="editor-section"><div className="editor-section-title"><span>03</span><div><b>Agent Chain</b><small>Discovery、Repair、Review 必须是显式角色，Review 使用独立 session</small></div></div><div className="form-grid three"><label>Discovery<select value={editor.agents?.discovery??''} onChange={e=>setEditor({...editor,agents:{...editor.agents,discovery:e.target.value}})}><option value="">选择 profile</option>{profileIds.map(id=><option key={id}>{id}</option>)}</select></label><label>Repair<select value={editor.agents?.repair??''} onChange={e=>setEditor({...editor,agents:{...editor.agents,repair:e.target.value}})}><option value="">选择 profile</option>{profileIds.map(id=><option key={id}>{id}</option>)}</select></label><label>Review<select value={editor.agents?.review??''} onChange={e=>setEditor({...editor,agents:{...editor.agents,review:e.target.value}})}><option value="">选择 profile</option>{profileIds.map(id=><option key={id}>{id}</option>)}</select></label></div></div>
  <div className="editor-section"><div className="editor-section-title"><span>04</span><div><b>验证门禁</b><small>Agent 自报“已测试”不算，平台只认真实命令退出码</small></div><button className="ghost framed" onClick={addVerification}>＋ 验证步骤</button></div>{(editor.verification?.steps??[]).map((step,index)=><div className="verification-row" key={`${step.id}-${index}`}><input value={step.id} onChange={e=>updateVerification(index,{id:e.target.value})} placeholder="unit"/><select value={step.executableRef} onChange={e=>updateVerification(index,{executableRef:e.target.value})}><option value="">executableRef</option>{executableIds.map(id=><option key={id}>{id}</option>)}</select><input value={step.args.join(' ')} onChange={e=>updateVerification(index,{args:e.target.value.split(' ').filter(Boolean)})} placeholder="-m pytest"/><input value={step.workingDirectory??'.'} onChange={e=>updateVerification(index,{workingDirectory:e.target.value})} placeholder="."/><button className="ghost" onClick={()=>setEditor({...editor,verification:{...editor.verification,steps:(editor.verification?.steps??[]).filter((_,i)=>i!==index)}})}>×</button></div>)}<label className="check-row"><input type="checkbox" checked={!!editor.verification?.allowNoAutomatedTests} onChange={e=>setEditor({...editor,verification:{...editor.verification,allowNoAutomatedTests:e.target.checked}})}/><span>当前没有自动测试，使用项目级显式替代门禁</span></label>{editor.verification?.allowNoAutomatedTests&&<label className="wide-label">替代门禁说明<textarea value={editor.verification.reason??''} onChange={e=>setEditor({...editor,verification:{...editor.verification,reason:e.target.value}})} placeholder="必须解释为什么仍可安全交付，以及采用什么替代证据"/></label>}</div>
  <div className="editor-section"><div className="editor-section-title"><span>05</span><div><b>最终动作</b><small>所有启用动作都是必需动作，并且消费同一份 Freeze Change</small></div></div><div className="segmented action-type"><button className={currentAction?.type!=='gitlabMr'?'selected':''} onClick={()=>setAction(patchAction(currentAction))}>Patch</button><button className={currentAction?.type==='gitlabMr'?'selected':''} onClick={()=>setAction(mrAction(currentAction))}>GitLab MR</button></div>{currentAction?.type==='gitlabMr'?<div className="form-grid"><label>Action ID<input value={currentMr.id} onChange={e=>setAction({...currentMr,id:e.target.value})}/></label><label>Connection<select value={currentMr.connectionRef} onChange={e=>setAction({...currentMr,connectionRef:e.target.value})}><option value="">选择 GitLab connection</option>{connectionIds.map(id=><option key={id}>{id}</option>)}</select></label><label>GitLab Project Path<input value={currentMr.projectPath} onChange={e=>setAction({...currentMr,projectPath:e.target.value})} placeholder="group/project"/></label><label>Materialization Repo<select value={currentMr.materializationRepositoryRef} onChange={e=>setAction({...currentMr,materializationRepositoryRef:e.target.value})}><option value="">选择 Git 仓库 pathBinding</option>{pathIds.map(id=><option key={id}>{id}</option>)}</select></label><label>目标分支<input value={currentMr.targetBranches.join(', ')} onChange={e=>setAction({...currentMr,targetBranches:csv(e.target.value)})} placeholder="main, release/4.7"/></label><label>Path Mapping<input value={(currentMr.pathMappings??[{from:'.',to:'.'}]).map(m=>`${m.from}:${m.to}`).join(', ')} onChange={e=>setAction({...currentMr,pathMappings:csv(e.target.value).map(pair=>{const[from,to]=pair.split(':');return{from:from||'.',to:to||'.'}})})} placeholder=".:. 或 Product/Lua:Assets/Lua"/></label></div>:<div className="form-grid"><label>Action ID<input value={currentPatch.id} onChange={e=>setAction({...currentPatch,id:e.target.value})}/></label><label>输出目录<select value={currentPatch.outputDirectoryRef} onChange={e=>setAction({...currentPatch,outputDirectoryRef:e.target.value})}>{pathIds.map(id=><option key={id}>{id}</option>)}</select></label><label>文件名模板<input value={currentPatch.filenameTemplate??''} onChange={e=>setAction({...currentPatch,filenameTemplate:e.target.value})}/></label></div>}</div>
  <div className="modal-actions sticky-actions"><button className="ghost" onClick={()=>setEditor(null)}>取消</button><button className="primary compact" disabled={busy||!editor.id||!route.providerRef||!editor.modificationSource?.repositoryRef||!editor.agents?.discovery||!editor.agents?.repair||!editor.agents?.review} onClick={()=>void save()}>{busy?'保存中…':'保存并进入 Preflight'}</button></div></div></div>}
  </section>
}
