import { useEffect, useMemo, useState } from 'react'
import { FinalActionsEditor } from '../components/FinalActionsEditor'
import type { PreflightResult, ProjectConfig, RoutingOperator, SettingsResponse, VerificationStepConfig } from '../entities/config'
import { ApiError, api } from '../lib/api'

const csv=(value:string)=>value.split(',').map(item=>item.trim()).filter(Boolean)
const emptyProject=():ProjectConfig=>({id:'',name:'',enabled:true,routingRules:[{id:'primary-route',providerRef:'',priority:100,catchAll:true,conditions:[]}],modificationSource:{id:'project-source',type:'git',repositoryRef:'',executableRef:'git-cli',allowedRoots:['.'],deniedRoots:[],allowedExtensions:[]},agents:{discovery:'',repair:'',review:''},verification:{timeoutSeconds:1200,steps:[],allowNoAutomatedTests:false,reason:''},finalActions:[{id:'primary-patch',type:'patch',outputDirectoryRef:'primary-patches',filenameTemplate:'{task_id}-{run_id}.patch',overwrite:false}]})
const firstRule=(p:ProjectConfig)=>p.routingRules?.[0]??{id:'primary-route',providerRef:'',priority:100,catchAll:true,conditions:[]}

export function ProjectsPage(){
 const[projects,setProjects]=useState<ProjectConfig[]>([]);const[settings,setSettings]=useState<SettingsResponse|null>(null);const[editor,setEditor]=useState<ProjectConfig|null>(null);const[preflights,setPreflights]=useState<Record<string,PreflightResult>>({});const[error,setError]=useState('');const[busy,setBusy]=useState(false)
 const reload=async()=>{const[p,s]=await Promise.all([api.projects(),api.settings()]);setProjects(p.items);setSettings(s)}
 useEffect(()=>{reload().catch(e=>setError(e instanceof Error?e.message:'加载失败'))},[])
 const profiles=useMemo(()=>settings?.config.agentProfiles.map(x=>x.id)??[],[settings]);const providers=useMemo(()=>settings?.config.ticketProviders.map(x=>x.id)??[],[settings]);const paths=useMemo(()=>Object.keys(settings?.config.pathBindings??{}),[settings]);const executables=useMemo(()=>Object.keys(settings?.config.executableBindings??{}),[settings]);const connections=useMemo(()=>settings?.config.connections.map(x=>x.id)??[],[settings])
 const updateRule=(patch:Partial<ReturnType<typeof firstRule>>)=>{if(editor)setEditor({...editor,routingRules:[{...firstRule(editor),...patch}]})}
 const updateSource=(patch:Partial<NonNullable<ProjectConfig['modificationSource']>>)=>{if(editor)setEditor({...editor,modificationSource:{...editor.modificationSource,...patch}})}
 const addVerification=()=>{if(!editor)return;const steps=editor.verification?.steps??[];const next:VerificationStepConfig={id:`step-${steps.length+1}`,executableRef:'',args:[],workingDirectory:'.',required:true};setEditor({...editor,verification:{...editor.verification,steps:[...steps,next]}})}
 const updateVerification=(i:number,patch:Partial<VerificationStepConfig>)=>{if(!editor)return;const steps=[...(editor.verification?.steps??[])];steps[i]={...steps[i],...patch};setEditor({...editor,verification:{...editor.verification,steps}})}
 const save=async()=>{if(!editor||!settings)return;setBusy(true);setError('');try{const r=await api.createProject(editor,settings.etag);setSettings({...settings,etag:r.etag});setEditor(null);await reload()}catch(e){setError(e instanceof ApiError?e.message:'保存失败')}finally{setBusy(false)}}
 const preflight=async(id:string)=>{setBusy(true);try{const r=await api.preflight(id);setPreflights(v=>({...v,[id]:r}))}catch(e){setError(e instanceof Error?e.message:'Preflight 失败')}finally{setBusy(false)}}
 const route=editor?firstRule(editor):null;const condition=route?.conditions?.[0]
 return <section className="page-stack"><div className="page-heading"><div><span className="eyebrow">PROJECT POLICY</span><h1>项目</h1><p>一条项目策略把工单确定性地收敛到唯一代码源，再经过 Agent Chain、验证与冻结交付。</p></div><button className="primary compact" onClick={()=>setEditor(emptyProject())}>＋ 新建项目</button></div>{error&&<button className="notice-strip error-note" onClick={()=>setError('')}>{error}</button>}
 {projects.length===0?<div className="empty-state"><span className="empty-mark">◇</span><h2>还没有项目</h2><p>先建立一条完整的可执行策略。CodeFixer 不会在路由不唯一时猜测修改源。</p><button className="primary compact" onClick={()=>setEditor(emptyProject())}>创建第一个项目</button></div>:<div className="project-grid">{projects.map(p=>{const pf=preflights[p.id];const r=p.routingRules?.[0];return <article className="project-card" key={p.id}><div className="project-card-head"><div><span className="ticket">{p.id}</span><h3>{p.name||p.id}</h3></div><span className={`readiness-badge ${pf?.ready?'ready':pf?'failed':'unknown'}`}>{pf?.ready?'READY':pf?'NOT READY':'UNCHECKED'}</span></div><div className="route-signature"><span>{r?.providerRef||'NO ROUTE'}</span><i>→</i><b>{p.modificationSource?.type?.toUpperCase()} · {p.modificationSource?.repositoryRef||'未绑定'}</b></div><div className="project-spec"><div><small>Agent Chain</small><b>{p.agents?.discovery||'—'} → {p.agents?.repair||'—'} → {p.agents?.review||'—'}</b></div><div><small>最终动作</small><b>{p.finalActions?.map(a=>a.type).join(' + ')||'未配置'}</b></div></div>{pf&&<div className="preflight-mini">{pf.checks.slice(0,8).map(c=><div key={c.id} className={c.status}><i/>{c.summary}</div>)}</div>}<button className="ghost action-link" disabled={busy} onClick={()=>void preflight(p.id)}>运行 Preflight →</button></article>})}</div>}
 {editor&&settings&&route&&<div className="modal-backdrop editor-backdrop"><div className="config-modal project-editor" role="dialog" aria-modal="true"><div className="modal-head"><div><span className="signal-kicker">PROJECT BLUEPRINT</span><h2>建立可执行项目</h2><p>保存前把路由、代码源、Agent、验证和所有必需交付动作收敛成一条闭环。</p></div><button className="icon-btn" onClick={()=>setEditor(null)} aria-label="关闭">×</button></div>
 <EditorSection n="01" title="项目身份与路由" sub="外部 Bug 必须确定性地只命中一个项目"><div className="form-grid"><Field label="项目 ID"><input value={editor.id} onChange={e=>setEditor({...editor,id:e.target.value})} placeholder="product-lua"/></Field><Field label="显示名称"><input value={editor.name??''} onChange={e=>setEditor({...editor,name:e.target.value})}/></Field><Field label="Provider"><select value={route.providerRef} onChange={e=>updateRule({providerRef:e.target.value})}><option value="">选择工单来源</option>{providers.map(id=><option key={id}>{id}</option>)}</select></Field><Field label="优先级"><input type="number" value={route.priority} onChange={e=>updateRule({priority:Number(e.target.value)||0})}/></Field></div><label className="check-row"><input type="checkbox" checked={!!route.catchAll} onChange={e=>updateRule({catchAll:e.target.checked,conditions:e.target.checked?[]:[{field:'module',operator:'contains',value:''}]})}/><span>这个 Provider 的工单全部路由到本项目（Catch All）</span></label>{!route.catchAll&&<div className="route-condition"><Field label="工单字段"><input value={String(condition?.field??'module')} onChange={e=>updateRule({conditions:[{field:e.target.value,operator:(condition?.operator??'contains') as RoutingOperator,value:condition?.value??''}]})}/></Field><Field label="条件"><select value={condition?.operator??'contains'} onChange={e=>updateRule({conditions:[{field:condition?.field??'module',operator:e.target.value as RoutingOperator,value:condition?.value??''}]})}><option value="contains">包含</option><option value="eq">等于</option><option value="neq">不等于</option><option value="exists">存在</option></select></Field><Field label="值"><input disabled={condition?.operator==='exists'} value={String(condition?.value??'')} onChange={e=>updateRule({conditions:[{field:condition?.field??'module',operator:(condition?.operator??'contains') as RoutingOperator,value:e.target.value}]})}/></Field></div>}</EditorSection>
 <EditorSection n="02" title="唯一修改源" sub="Agent 只能在这一份隔离代码空间内工作"><div className="form-grid"><Field label="类型"><select value={editor.modificationSource?.type} onChange={e=>updateSource({type:e.target.value as 'git'|'svn',executableRef:e.target.value==='git'?'git-cli':'svn-cli'})}><option value="git">Git</option><option value="svn">SVN</option></select></Field><Field label="Repository Ref"><select value={editor.modificationSource?.repositoryRef??''} onChange={e=>updateSource({repositoryRef:e.target.value})}><option value="">选择 pathBinding</option>{paths.map(id=><option key={id}>{id}</option>)}</select></Field><Field label="CLI Ref"><select value={editor.modificationSource?.executableRef??''} onChange={e=>updateSource({executableRef:e.target.value})}>{executables.map(id=><option key={id}>{id}</option>)}</select></Field><Field label="允许扩展名"><input value={(editor.modificationSource?.allowedExtensions??[]).join(', ')} onChange={e=>updateSource({allowedExtensions:csv(e.target.value)})} placeholder=".py, .ts, .lua；留空=不限"/></Field><Field label="允许根目录"><input value={(editor.modificationSource?.allowedRoots??['.']).join(', ')} onChange={e=>updateSource({allowedRoots:csv(e.target.value)})}/></Field><Field label="禁止根目录"><input value={(editor.modificationSource?.deniedRoots??[]).join(', ')} onChange={e=>updateSource({deniedRoots:csv(e.target.value)})}/></Field></div></EditorSection>
 <EditorSection n="03" title="Agent Chain" sub="Discovery、Repair、Review 是显式独立角色"><div className="form-grid three">{(['discovery','repair','review'] as const).map(role=><Field label={role} key={role}><select value={editor.agents?.[role]??''} onChange={e=>setEditor({...editor,agents:{...editor.agents,[role]:e.target.value}})}><option value="">选择 profile</option>{profiles.map(id=><option key={id}>{id}</option>)}</select></Field>)}</div></EditorSection>
 <EditorSection n="04" title="验证门禁" sub="平台只认真实命令退出码" extra={<button className="ghost framed" onClick={addVerification}>＋ 验证步骤</button>}>{(editor.verification?.steps??[]).map((step,i)=><div className="verification-row" key={`${step.id}-${i}`}><input value={step.id} onChange={e=>updateVerification(i,{id:e.target.value})}/><select value={step.executableRef} onChange={e=>updateVerification(i,{executableRef:e.target.value})}><option value="">executableRef</option>{executables.map(id=><option key={id}>{id}</option>)}</select><input value={step.args.join(' ')} onChange={e=>updateVerification(i,{args:e.target.value.split(' ').filter(Boolean)})} placeholder="-m pytest"/><input value={step.workingDirectory??'.'} onChange={e=>updateVerification(i,{workingDirectory:e.target.value})}/><button className="ghost" onClick={()=>setEditor({...editor,verification:{...editor.verification,steps:(editor.verification?.steps??[]).filter((_,x)=>x!==i)}})}>×</button></div>)}<label className="check-row"><input type="checkbox" checked={!!editor.verification?.allowNoAutomatedTests} onChange={e=>setEditor({...editor,verification:{...editor.verification,allowNoAutomatedTests:e.target.checked}})}/><span>当前没有自动测试，使用项目级显式替代门禁</span></label>{editor.verification?.allowNoAutomatedTests&&<label className="wide-label">替代门禁说明<textarea value={editor.verification.reason??''} onChange={e=>setEditor({...editor,verification:{...editor.verification,reason:e.target.value}})}/></label>}</EditorSection>
 <EditorSection n="05" title="最终动作" sub="可同时启用 Patch + GitLab MR；全部消费同一份 Freeze Change"><FinalActionsEditor actions={editor.finalActions??[]} pathIds={paths} connectionIds={connections} onChange={actions=>setEditor({...editor,finalActions:actions})}/></EditorSection>
 <div className="modal-actions sticky-actions"><button className="ghost" onClick={()=>setEditor(null)}>取消</button><button className="primary compact" disabled={busy||!editor.id||!route.providerRef||!editor.modificationSource?.repositoryRef||!editor.agents?.discovery||!editor.agents?.repair||!editor.agents?.review||!(editor.finalActions?.length)} onClick={()=>void save()}>{busy?'保存中…':'保存并进入 Preflight'}</button></div></div></div>}</section>
}

function EditorSection({n,title,sub,extra,children}:{n:string;title:string;sub:string;extra?:React.ReactNode;children:React.ReactNode}){return <div className="editor-section"><div className="editor-section-title"><span>{n}</span><div><b>{title}</b><small>{sub}</small></div>{extra}</div>{children}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label>{label}{children}</label>}
