import { useEffect, useMemo, useState } from 'react'
import type { AgentProfileConfig, FinalActionConfig, GitLabMrActionConfig, PatchActionConfig, PreflightResult, ProjectConfig, RoutingOperator, SettingsResponse, VerificationStepConfig } from '../entities/config'
import { ApiError, api } from '../lib/api'

const emptyProject = (): ProjectConfig => ({
  id: '', name: '', enabled: true,
  routingRules: [{ id: 'primary-route', providerRef: '', priority: 100, catchAll: true, conditions: [] }],
  modificationSource: { id: 'project-source', type: 'git', repositoryRef: '', executableRef: 'git-cli', allowedRoots: ['.'], deniedRoots: [], allowedExtensions: [] },
  agents: { scopeDiscovery: '', discovery: '', repair: '', review: '' },
  verification: { timeoutSeconds: 1200, steps: [], allowNoAutomatedTests: false, reason: '' },
  finalActions: [{ id: 'primary-patch', type: 'patch', outputDirectoryRef: 'primary-patches', filenameTemplate: '{task_id}-{run_id}.patch', overwrite: false }],
})
const csv=(value:string)=>value.split(',').map(item=>item.trim()).filter(Boolean)
const firstRule=(project:ProjectConfig)=>project.routingRules?.[0]??{id:'primary-route',providerRef:'',priority:100,catchAll:true,conditions:[]}
const patchAction=(action:FinalActionConfig|undefined):PatchActionConfig=>action?.type==='patch'?action:{id:'primary-patch',type:'patch',outputDirectoryRef:'primary-patches',filenameTemplate:'{task_id}-{run_id}.patch',overwrite:false}
const mrAction=(action:FinalActionConfig|undefined):GitLabMrActionConfig=>action?.type==='gitlabMr'?action:{id:'main-gitlab-mr',type:'gitlabMr',connectionRef:'',projectPath:'',materializationRepositoryRef:'git-materialization',gitExecutableRef:'git-cli',targetBranches:['main'],pathMappings:[{from:'.',to:'.'}],titleTemplate:'[CodeFixer] {task_id}',descriptionTemplate:'CodeFixer 自动修复任务 {run_id}。'}
const actionLabel=(action:FinalActionConfig)=>action.type==='patch'?'生成补丁':'创建合并请求'
const profileOptionLabel=(profile:AgentProfileConfig)=>{
  if(profile.runtime==='claudeCode'){
    if(!profile.model)return 'Claude Code · 默认模型'
    if(profile.model==='sonnet')return 'Claude Sonnet'
    if(profile.model==='opus')return 'Claude Opus'
    return `Claude · ${profile.model}`
  }
  const runtime=profile.runtime==='codex'?'Codex':'OpenCode'
  return `${runtime}${profile.model?` · ${profile.model}`:' · 默认模型'}`
}

export function ProjectsPage() {
  const [projects,setProjects]=useState<ProjectConfig[]>([]);const [settings,setSettings]=useState<SettingsResponse|null>(null);const [editor,setEditor]=useState<ProjectConfig|null>(null);const [preflights,setPreflights]=useState<Record<string,PreflightResult>>({});const [error,setError]=useState('');const [busy,setBusy]=useState(false)
  const reload=async()=>{const[p,s]=await Promise.all([api.projects(),api.settings()]);setProjects(p.items);setSettings(s)}
  useEffect(()=>{reload().catch(e=>setError(e instanceof Error?e.message:'加载失败'))},[])
  const profiles=useMemo(()=>settings?.config.agentProfiles.filter(p=>p.id)??[],[settings]);const providerIds=useMemo(()=>settings?.config.ticketProviders.map(p=>p.id).filter(Boolean)??[],[settings]);const connectionIds=useMemo(()=>settings?.config.connections.map(p=>p.id).filter(Boolean)??[],[settings]);const pathIds=useMemo(()=>Object.keys(settings?.config.pathBindings??{}),[settings]);const executableIds=useMemo(()=>Object.keys(settings?.config.executableBindings??{}),[settings])
  const updateRule=(patch:Partial<NonNullable<ProjectConfig['routingRules']>[number]>)=>{if(!editor)return;setEditor({...editor,routingRules:[{...firstRule(editor),...patch}]})}
  const updateSource=(patch:Partial<NonNullable<ProjectConfig['modificationSource']>>)=>editor&&setEditor({...editor,modificationSource:{...editor.modificationSource,...patch}})
  const setAction=(action:FinalActionConfig)=>editor&&setEditor({...editor,finalActions:[action]})
  const save=async()=>{if(!editor||!settings)return;setBusy(true);setError('');try{const result=await api.createProject(editor,settings.etag);setSettings({...settings,etag:result.etag});setEditor(null);await reload()}catch(e){setError(e instanceof ApiError?e.message:'保存失败')}finally{setBusy(false)}}
  const preflight=async(id:string)=>{setBusy(true);try{const result=await api.preflight(id);setPreflights(v=>({...v,[id]:result}))}catch(e){setError(e instanceof Error?e.message:'检查失败')}finally{setBusy(false)}}
  const addVerification=()=>{if(!editor)return;const steps=editor.verification?.steps??[];const step:VerificationStepConfig={id:`step-${steps.length+1}`,executableRef:'',args:[],workingDirectory:'.',required:true};setEditor({...editor,verification:{...editor.verification,steps:[...steps,step]}})}
  const updateVerification=(index:number,patch:Partial<VerificationStepConfig>)=>{if(!editor)return;const steps=[...(editor.verification?.steps??[])];steps[index]={...steps[index],...patch};setEditor({...editor,verification:{...editor.verification,steps}})}
  const currentAction=editor?.finalActions?.[0];const currentPatch=patchAction(currentAction);const currentMr=mrAction(currentAction);const route=editor?firstRule(editor):null;const routeCondition=route?.conditions?.[0]
  return <section className="page-stack"><div className="page-heading"><div><h1>项目</h1><p>把一类工单和一份代码仓库绑定在一起。</p></div><button className="primary compact" onClick={()=>setEditor(emptyProject())}>新建项目</button></div>{error&&<button className="notice-strip error-note" onClick={()=>setError('')}>{error}</button>}
  {projects.length===0?<div className="empty-state"><h2>还没有项目</h2><p>创建项目后，CodeFixer 才知道新工单应该修改哪份代码。</p><button className="primary compact" onClick={()=>setEditor(emptyProject())}>创建项目</button></div>:<div className="project-grid">{projects.map(project=>{const pf=preflights[project.id];return <article className="project-card project-card-simple" key={project.id}><div className="project-card-head"><div><small>{project.id}</small><h3>{project.name||project.id}</h3></div><span className={`readiness-badge ${pf?.ready?'ready':pf?'failed':'unknown'}`}>{pf?.ready?'可用':pf?'需检查':'未检查'}</span></div><div className="project-summary"><span>{project.modificationSource?.type==='svn'?'SVN':'Git'}</span><span>{project.finalActions?.[0]?actionLabel(project.finalActions[0]):'未配置交付'}</span></div><button className="ghost action-link" disabled={busy} onClick={()=>void preflight(project.id)}>检查配置</button></article>})}</div>}
  {editor&&settings&&route&&<div className="modal-backdrop editor-backdrop"><div className="config-modal project-editor project-editor-simple" role="dialog" aria-modal="true" aria-labelledby="project-editor-title"><div className="modal-head"><div><h2 id="project-editor-title">新建项目</h2><p>先完成必要信息，其他规则可以稍后在高级设置中调整。</p></div><button className="icon-btn" onClick={()=>setEditor(null)} aria-label="关闭">×</button></div>
  <div className="editor-section"><div className="editor-section-title"><span>1</span><div><b>基本信息</b></div></div><div className="form-grid"><label>项目名称<input value={editor.name??''} onChange={e=>setEditor({...editor,name:e.target.value})} placeholder="例如：战双 Lua"/></label><label>项目 ID<input value={editor.id} onChange={e=>setEditor({...editor,id:e.target.value})} placeholder="product-lua"/></label><label>工单来源<select value={route.providerRef} onChange={e=>updateRule({providerRef:e.target.value})}><option value="">选择来源</option>{providerIds.map(id=><option key={id}>{id}</option>)}</select></label><label>代码类型<select value={editor.modificationSource?.type} onChange={e=>updateSource({type:e.target.value as 'git'|'svn',executableRef:e.target.value==='git'?'git-cli':'svn-cli'})}><option value="git">Git</option><option value="svn">SVN</option></select></label><label className="span-field">代码位置<select value={editor.modificationSource?.repositoryRef??''} onChange={e=>updateSource({repositoryRef:e.target.value})}><option value="">选择本机路径</option>{pathIds.map(id=><option key={id}>{id}</option>)}</select></label></div></div>
  <div className="editor-section"><div className="editor-section-title"><span>2</span><div><b>AI 助手</b><small>范围调查与正式定位是两个独立会话</small></div></div><div className="form-grid four"><label>范围调查<select value={editor.agents?.scopeDiscovery??''} onChange={e=>setEditor({...editor,agents:{...editor.agents,scopeDiscovery:e.target.value}})}><option value="">选择模型</option>{profiles.map(profile=><option key={profile.id} value={profile.id}>{profileOptionLabel(profile)}</option>)}</select></label><label>正式定位<select value={editor.agents?.discovery??''} onChange={e=>setEditor({...editor,agents:{...editor.agents,discovery:e.target.value}})}><option value="">选择模型</option>{profiles.map(profile=><option key={profile.id} value={profile.id}>{profileOptionLabel(profile)}</option>)}</select></label><label>修复<select value={editor.agents?.repair??''} onChange={e=>setEditor({...editor,agents:{...editor.agents,repair:e.target.value}})}><option value="">选择模型</option>{profiles.map(profile=><option key={profile.id} value={profile.id}>{profileOptionLabel(profile)}</option>)}</select></label><label>复核<select value={editor.agents?.review??''} onChange={e=>setEditor({...editor,agents:{...editor.agents,review:e.target.value}})}><option value="">选择模型</option>{profiles.map(profile=><option key={profile.id} value={profile.id}>{profileOptionLabel(profile)}</option>)}</select></label></div></div>
  <div className="editor-section"><div className="editor-section-title"><span>3</span><div><b>交付方式</b></div></div><div className="segmented action-type"><button className={currentAction?.type!=='gitlabMr'?'selected':''} onClick={()=>setAction(patchAction(currentAction))}>生成补丁</button><button className={currentAction?.type==='gitlabMr'?'selected':''} onClick={()=>setAction(mrAction(currentAction))}>GitLab 合并请求</button></div>{currentAction?.type==='gitlabMr'?<div className="form-grid compact-action-form"><label>GitLab 连接<select value={currentMr.connectionRef} onChange={e=>setAction({...currentMr,connectionRef:e.target.value})}><option value="">选择连接</option>{connectionIds.map(id=><option key={id}>{id}</option>)}</select></label><label>仓库路径<input value={currentMr.projectPath} onChange={e=>setAction({...currentMr,projectPath:e.target.value})} placeholder="group/project"/></label><label>目标分支<input value={currentMr.targetBranches.join(', ')} onChange={e=>setAction({...currentMr,targetBranches:csv(e.target.value)})} placeholder="main, release/1.0"/></label></div>:<div className="form-grid compact-action-form"><label>补丁保存位置<select value={currentPatch.outputDirectoryRef} onChange={e=>setAction({...currentPatch,outputDirectoryRef:e.target.value})}>{pathIds.map(id=><option key={id}>{id}</option>)}</select></label></div>}</div>
  <details className="settings-advanced project-advanced"><summary>高级设置</summary><div className="advanced-project-body"><h3>路由规则</h3><div className="form-grid"><label>优先级<input type="number" value={route.priority} onChange={e=>updateRule({priority:Number(e.target.value)||0})}/></label><label className="check-row"><input type="checkbox" checked={!!route.catchAll} onChange={e=>updateRule({catchAll:e.target.checked,conditions:e.target.checked?[]:[{field:'module',operator:'contains',value:''}]})}/><span>接收这个来源的全部工单</span></label></div>{!route.catchAll&&<div className="route-condition"><label>字段<input value={String(routeCondition?.field??'module')} onChange={e=>updateRule({conditions:[{field:e.target.value,operator:(routeCondition?.operator??'contains') as RoutingOperator,value:routeCondition?.value??''}]})}/></label><label>条件<select value={routeCondition?.operator??'contains'} onChange={e=>updateRule({conditions:[{field:routeCondition?.field??'module',operator:e.target.value as RoutingOperator,value:routeCondition?.value??''}]})}><option value="contains">包含</option><option value="eq">等于</option><option value="neq">不等于</option><option value="exists">存在</option></select></label><label>值<input disabled={routeCondition?.operator==='exists'} value={String(routeCondition?.value??'')} onChange={e=>updateRule({conditions:[{field:routeCondition?.field??'module',operator:(routeCondition?.operator??'contains') as RoutingOperator,value:e.target.value}]})}/></label></div>}
  <h3>代码限制</h3><div className="form-grid"><label>命令<select value={editor.modificationSource?.executableRef??''} onChange={e=>updateSource({executableRef:e.target.value})}>{executableIds.map(id=><option key={id}>{id}</option>)}</select></label><label>允许扩展名<input value={(editor.modificationSource?.allowedExtensions??[]).join(', ')} onChange={e=>updateSource({allowedExtensions:csv(e.target.value)})} placeholder=".py, .ts, .lua"/></label><label>允许目录<input value={(editor.modificationSource?.allowedRoots??['.']).join(', ')} onChange={e=>updateSource({allowedRoots:csv(e.target.value)})}/></label><label>禁止目录<input value={(editor.modificationSource?.deniedRoots??[]).join(', ')} onChange={e=>updateSource({deniedRoots:csv(e.target.value)})}/></label></div>
  <div className="advanced-heading"><h3>验证命令</h3><button className="ghost framed" onClick={addVerification}>添加</button></div>{(editor.verification?.steps??[]).map((step,index)=><div className="verification-row" key={`${step.id}-${index}`}><input value={step.id} onChange={e=>updateVerification(index,{id:e.target.value})} placeholder="名称"/><select value={step.executableRef} onChange={e=>updateVerification(index,{executableRef:e.target.value})}><option value="">选择命令</option>{executableIds.map(id=><option key={id}>{id}</option>)}</select><input value={step.args.join(' ')} onChange={e=>updateVerification(index,{args:e.target.value.split(' ').filter(Boolean)})} placeholder="参数"/><input value={step.workingDirectory??'.'} onChange={e=>updateVerification(index,{workingDirectory:e.target.value})} placeholder="工作目录"/><button className="ghost" onClick={()=>setEditor({...editor,verification:{...editor.verification,steps:(editor.verification?.steps??[]).filter((_,i)=>i!==index)}})}>×</button></div>)}<label className="check-row"><input type="checkbox" checked={!!editor.verification?.allowNoAutomatedTests} onChange={e=>setEditor({...editor,verification:{...editor.verification,allowNoAutomatedTests:e.target.checked}})}/><span>当前没有自动测试</span></label>{editor.verification?.allowNoAutomatedTests&&<label className="wide-label">说明<textarea value={editor.verification.reason??''} onChange={e=>setEditor({...editor,verification:{...editor.verification,reason:e.target.value}})}/></label>}</div></details>
  <div className="modal-actions sticky-actions"><button className="ghost" onClick={()=>setEditor(null)}>取消</button><button className="primary compact" disabled={busy||!editor.id||!route.providerRef||!editor.modificationSource?.repositoryRef||!editor.agents?.scopeDiscovery||!editor.agents?.discovery||!editor.agents?.repair||!editor.agents?.review||!currentAction} onClick={()=>void save()}>{busy?'保存中…':'保存并检查'}</button></div></div></div>}
  </section>
}
