import { useEffect, useState } from 'react'
import type { SettingsResponse, TicketProviderConfig } from '../entities/config'
import { api } from '../lib/api'

export function ProvidersPage(){
 const[settings,setSettings]=useState<SettingsResponse|null>(null);const[providers,setProviders]=useState<TicketProviderConfig[]>([]);const[notice,setNotice]=useState('');const[busy,setBusy]=useState('');const[show,setShow]=useState(false)
 const[type,setType]=useState<'redmine'|'tapd'>('redmine');const[id,setId]=useState('');const[baseUrl,setBaseUrl]=useState('');const[workspaceId,setWorkspaceId]=useState('');const[authMode,setAuthMode]=useState<'basic'|'oauth'>('basic');const[secretA,setSecretA]=useState('');const[secretB,setSecretB]=useState('')
 const load=async()=>{try{const[s,p]=await Promise.all([api.settings(),api.providers()]);setSettings(s);setProviders(p.items as TicketProviderConfig[])}catch(e){setNotice(e instanceof Error?e.message:'来源加载失败')}}
 useEffect(()=>{void load()},[])
 const action=async(providerId:string,kind:'test'|'poll')=>{setBusy(`${kind}:${providerId}`);try{const r=kind==='test'?await api.testProvider(providerId):await api.pollProvider(providerId);setNotice(kind==='test'?'连接正常':`收单完成${typeof r==='object'?'':''}`);await load()}catch(e){setNotice(e instanceof Error?e.message:'操作失败')}finally{setBusy('')}}
 const reset=()=>{setShow(false);setId('');setBaseUrl('');setWorkspaceId('');setAuthMode('basic');setSecretA('');setSecretB('')}
 const add=async()=>{if(!settings||!id)return;const provider:TicketProviderConfig=type==='redmine'?{id,type,enabled:true,baseUrl,apiKeySecretRef:secretA,pollIntervalSeconds:60}:{id,type,enabled:true,workspaceId,auth:authMode==='basic'?{mode:'basic',usernameSecretRef:secretA,passwordSecretRef:secretB}:{mode:'oauth',tokenSecretRef:secretA},pollIntervalSeconds:60};const config={...settings.config,ticketProviders:[...settings.config.ticketProviders,provider]};try{const next=await api.putSettings(config,settings.etag);setSettings(next);setNotice('来源已添加');reset();await load()}catch(e){setNotice(e instanceof Error?e.message:'保存失败')}}
 return <section className="page-stack"><div className="page-heading"><div><h1>工单来源</h1><p>连接 Redmine 或 TAPD，CodeFixer 会自动收取新的问题。</p></div><button className="primary compact" onClick={()=>setShow(true)}>添加来源</button></div>{notice&&<button className="notice-strip" onClick={()=>setNotice('')}>{notice}</button>}
 {providers.length===0?<div className="empty-state"><h2>还没有工单来源</h2><p>添加一个来源后即可开始收单。</p></div>:<div className="provider-grid">{providers.map(p=><article className="provider-card provider-card-simple" key={p.id}><div className="provider-orbit"><span>{p.type==='tapd'?'T':'R'}</span></div><div className="provider-body"><small>{p.type==='tapd'?'TAPD':'Redmine'}</small><h2>{p.id}</h2><div className="provider-meta"><span><i className={p.enabled===false?'':'ready-dot'}/>{p.enabled===false?'已停用':'正常'}</span></div></div><div className="provider-actions"><button className="ghost framed" disabled={!!busy} onClick={()=>void action(p.id,'test')}>{busy===`test:${p.id}`?'测试中…':'测试连接'}</button><button className="primary compact" disabled={!!busy} onClick={()=>void action(p.id,'poll')}>{busy===`poll:${p.id}`?'收取中…':'立即收单'}</button></div></article>)}</div>}
 {show&&<div className="modal-backdrop"><div className="config-modal"><div className="modal-head"><div><h2>添加工单来源</h2></div><button className="icon-btn" onClick={reset} aria-label="关闭">×</button></div><div className="form-grid"><label>类型<select value={type} onChange={e=>setType(e.target.value as 'redmine'|'tapd')}><option value="redmine">Redmine</option><option value="tapd">TAPD</option></select></label><label>来源名称<input value={id} onChange={e=>setId(e.target.value)} placeholder="例如：公司 Redmine"/></label>{type==='redmine'?<><label>服务地址<input value={baseUrl} onChange={e=>setBaseUrl(e.target.value)} placeholder="https://redmine.example.com"/></label><label>API Key 凭据名称<input value={secretA} onChange={e=>setSecretA(e.target.value)} placeholder="redmine-api-key"/></label></>:<><label>工作区 ID<input value={workspaceId} onChange={e=>setWorkspaceId(e.target.value)} placeholder="10101010"/></label><label>登录方式<select value={authMode} onChange={e=>setAuthMode(e.target.value as 'basic'|'oauth')}><option value="basic">账号密码</option><option value="oauth">OAuth</option></select></label>{authMode==='basic'?<><label>账号凭据名称<input value={secretA} onChange={e=>setSecretA(e.target.value)} placeholder="tapd-user"/></label><label>密码凭据名称<input value={secretB} onChange={e=>setSecretB(e.target.value)} placeholder="tapd-password"/></label></>:<label>Token 凭据名称<input value={secretA} onChange={e=>setSecretA(e.target.value)} placeholder="tapd-access-token"/></label>}</>}</div><p className="form-hint">这里填写的是凭据名称，真实密码或 Token 在「设置 → 凭据」中保存。</p><div className="modal-actions"><button className="ghost" onClick={reset}>取消</button><button className="primary compact" disabled={!id||(type==='redmine'&&(!baseUrl||!secretA))||(type==='tapd'&&(!workspaceId||!secretA||(authMode==='basic'&&!secretB)))} onClick={()=>void add()}>保存</button></div></div></div>}
 </section>
}
