import { useEffect, useState } from 'react'
import type { SettingsResponse, TicketProviderConfig } from '../entities/config'
import { api } from '../lib/api'

export function ProvidersPage(){
 const[settings,setSettings]=useState<SettingsResponse|null>(null);const[providers,setProviders]=useState<TicketProviderConfig[]>([]);const[notice,setNotice]=useState('');const[busy,setBusy]=useState('');const[show,setShow]=useState(false)
 const[type,setType]=useState<'redmine'|'tapd'>('redmine');const[id,setId]=useState('');const[baseUrl,setBaseUrl]=useState('');const[workspaceId,setWorkspaceId]=useState('');const[authMode,setAuthMode]=useState<'basic'|'oauth'>('basic');const[secretA,setSecretA]=useState('');const[secretB,setSecretB]=useState('')
 const load=async()=>{try{const[s,p]=await Promise.all([api.settings(),api.providers()]);setSettings(s);setProviders(p.items as TicketProviderConfig[])}catch(e){setNotice(e instanceof Error?e.message:'来源加载失败')}}
 useEffect(()=>{void load()},[])
 const action=async(providerId:string,kind:'test'|'poll')=>{setBusy(`${kind}:${providerId}`);try{const r=kind==='test'?await api.testProvider(providerId):await api.pollProvider(providerId);setNotice(kind==='test'?`连接成功 · ${providerId}`:`轮询完成 · ${JSON.stringify(r)}`);await load()}catch(e){setNotice(e instanceof Error?e.message:'操作失败')}finally{setBusy('')}}
 const reset=()=>{setShow(false);setId('');setBaseUrl('');setWorkspaceId('');setAuthMode('basic');setSecretA('');setSecretB('')}
 const add=async()=>{if(!settings||!id)return;const provider:TicketProviderConfig=type==='redmine'?{id,type,enabled:true,baseUrl,apiKeySecretRef:secretA,pollIntervalSeconds:60}:{id,type,enabled:true,workspaceId,auth:authMode==='basic'?{mode:'basic',usernameSecretRef:secretA,passwordSecretRef:secretB}:{mode:'oauth',tokenSecretRef:secretA},pollIntervalSeconds:60};const config={...settings.config,ticketProviders:[...settings.config.ticketProviders,provider]};try{const next=await api.putSettings(config,settings.etag);setSettings(next);setNotice(`已添加 ${id}`);reset();await load()}catch(e){setNotice(e instanceof Error?e.message:'保存失败')}}
 return <section className="page-stack"><div className="page-heading"><div><span className="eyebrow">TICKET PROVIDERS</span><h1>工单来源</h1><p>这里只负责只读收单、冻结证据和稳定游标；Provider 无权修改工单。</p></div><button className="primary compact" onClick={()=>setShow(true)}>＋ 添加来源</button></div>{notice&&<button className="notice-strip" onClick={()=>setNotice('')}>{notice}</button>}
 {providers.length===0?<div className="empty-state"><span className="empty-mark">⇄</span><h2>还没有工单来源</h2><p>连接 Redmine 或 TAPD 后，CodeFixer 会持续轮询并把同一外部 Bug 保持为一个长期 Task。</p></div>:<div className="provider-grid">{providers.map(p=><article className="provider-card" key={p.id}><div className="provider-orbit"><span>{p.type==='tapd'?'T':'R'}</span></div><div className="provider-body"><span className="signal-kicker">{p.type.toUpperCase()}</span><h2>{p.id}</h2><p>{p.type==='redmine'?String(p.baseUrl??'Redmine'):`Workspace ${String(p.workspaceId??'—')}`}</p><div className="provider-meta"><span><i className={p.enabled===false?'':'ready-dot'}/>{p.enabled===false?'已停用':'正在监听'}</span><code>{String(p.pollIntervalSeconds??60)}s</code></div></div><div className="provider-actions"><button className="ghost framed" disabled={!!busy} onClick={()=>void action(p.id,'test')}>{busy===`test:${p.id}`?'测试中…':'测试连接'}</button><button className="primary compact" disabled={!!busy} onClick={()=>void action(p.id,'poll')}>{busy===`poll:${p.id}`?'轮询中…':'立即收单'}</button></div></article>)}</div>}
 {show&&<div className="modal-backdrop"><div className="config-modal"><div className="modal-head"><div><span className="signal-kicker">NEW PROVIDER</span><h2>添加工单来源</h2></div><button className="icon-btn" onClick={reset} aria-label="关闭">×</button></div><div className="form-grid"><label>类型<select value={type} onChange={e=>setType(e.target.value as 'redmine'|'tapd')}><option value="redmine">Redmine</option><option value="tapd">TAPD</option></select></label><label>Provider ID<input value={id} onChange={e=>setId(e.target.value)} placeholder="company-redmine"/></label>{type==='redmine'?<><label>Base URL<input value={baseUrl} onChange={e=>setBaseUrl(e.target.value)} placeholder="https://redmine.example.com"/></label><label>API Key Secret Ref<input value={secretA} onChange={e=>setSecretA(e.target.value)} placeholder="redmine-api-key"/></label></>:<><label>Workspace ID<input value={workspaceId} onChange={e=>setWorkspaceId(e.target.value)} placeholder="10101010"/></label><label>鉴权方式<select value={authMode} onChange={e=>setAuthMode(e.target.value as 'basic'|'oauth')}><option value="basic">Basic Auth</option><option value="oauth">OAuth Bearer</option></select></label>{authMode==='basic'?<><label>Username Secret Ref<input value={secretA} onChange={e=>setSecretA(e.target.value)} placeholder="tapd-user"/></label><label>Password Secret Ref<input value={secretB} onChange={e=>setSecretB(e.target.value)} placeholder="tapd-password"/></label></>:<label>OAuth Token Secret Ref<input value={secretA} onChange={e=>setSecretA(e.target.value)} placeholder="tapd-access-token"/></label>}</>}</div><p className="form-hint">Secret 这里只保存引用名；真实值去「系统设置 → 凭据保险箱」填写。TAPD OAuth token 到期后只需替换 Secret，不改项目。</p><div className="modal-actions"><button className="ghost" onClick={reset}>取消</button><button className="primary compact" disabled={!id||(type==='redmine'&&(!baseUrl||!secretA))||(type==='tapd'&&(!workspaceId||!secretA||(authMode==='basic'&&!secretB)))} onClick={()=>void add()}>保存来源</button></div></div></div>}
 </section>
}
