import { useEffect, useMemo, useState } from 'react'
import type { AgentProfileConfig, AgentRuntime, ConnectionConfig, ExecutionMode, SettingsResponse } from '../entities/config'
import { api } from '../lib/api'

type DraftAgent = AgentProfileConfig
type DraftConnection = ConnectionConfig
const emptyAgent = (): DraftAgent => ({ id: '', runtime: 'claudeCode', executableRef: 'claude-code-cli', timeoutSeconds: 1800 })
const emptyConnection = (): DraftConnection => ({ id: '', type: 'gitlab', baseUrl: '', tokenSecretRef: '' })

export function SettingsPage({ onModeChanged }:{ onModeChanged:(mode:ExecutionMode,etag:string)=>void }) {
  const [settings,setSettings]=useState<SettingsResponse|null>(null);const [secretKey,setSecretKey]=useState('');const [secretValue,setSecretValue]=useState('');const [pathId,setPathId]=useState('');const [pathValue,setPathValue]=useState('');const [agent,setAgent]=useState<DraftAgent|null>(null);const [connection,setConnection]=useState<DraftConnection|null>(null);const [notice,setNotice]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false)
  const load=async()=>{const next=await api.settings();setSettings(next)}
  useEffect(()=>{ load().catch(e=>setError(e instanceof Error?e.message:'加载失败')) },[])
  const executableIds=useMemo(()=>Object.keys(settings?.config.executableBindings??{}),[settings])
  if(!settings) return <section className="page-stack"><div className="page-heading"><div><span className="eyebrow">SYSTEM CONFIG</span><h1>系统设置</h1><p>{error||'正在读取配置…'}</p></div></div></section>
  const put=async(config:SettingsResponse['config'],message:string)=>{setBusy(true);setError('');try{const next=await api.putSettings(config,settings.etag);setSettings(next);setNotice(message);return next}catch(e){setError(e instanceof Error?e.message:'保存失败');return null}finally{setBusy(false)}}
  const changeMode=async(mode:ExecutionMode)=>{setBusy(true);setError('');try{const r=await api.setExecutionMode(mode,settings.etag);const next={...settings,config:{...settings.config,execution:{...settings.config.execution,mode}},etag:r.etag};setSettings(next);onModeChanged(mode,r.etag);setNotice('执行模式已保存')}catch(e){setError(e instanceof Error?e.message:'模式保存失败')}finally{setBusy(false)}}
  const saveSecret=async()=>{if(!secretKey||!secretValue)return;setBusy(true);try{await api.setSecret(secretKey,secretValue);setSettings({...settings,secrets:{...settings.secrets,[secretKey]:{configured:true}}});setSecretValue('');setNotice(`Secret ${secretKey} 已安全保存`)}catch(e){setError(e instanceof Error?e.message:'Secret 保存失败')}finally{setBusy(false)}}
  const savePath=async()=>{if(!pathId||!pathValue)return;const next=await put({...settings.config,pathBindings:{...settings.config.pathBindings,[pathId]:pathValue}},`Path Binding ${pathId} 已保存`);if(next){setPathId('');setPathValue('')}}
  const saveAgent=async()=>{if(!agent?.id||!agent.executableRef)return;const exists=settings.config.agentProfiles.some(item=>item.id===agent.id);if(exists){setError(`Agent Profile 已存在：${agent.id}`);return}const next=await put({...settings.config,agentProfiles:[...settings.config.agentProfiles,agent]},`Agent Profile ${agent.id} 已保存`);if(next)setAgent(null)}
  const saveConnection=async()=>{if(!connection?.id||!connection.baseUrl||!connection.tokenSecretRef)return;const exists=settings.config.connections.some(item=>item.id===connection.id);if(exists){setError(`Connection 已存在：${connection.id}`);return}const next=await put({...settings.config,connections:[...settings.config.connections,connection]},`GitLab Connection ${connection.id} 已保存`);if(next)setConnection(null)}
  const changeRuntime=(runtime:AgentRuntime)=>setAgent(current=>current?{...current,runtime,executableRef:runtime==='claudeCode'?'claude-code-cli':runtime==='codex'?'codex-cli':'opencode-cli'}:current)
  return <section className="page-stack"><div className="page-heading"><div><span className="eyebrow">SYSTEM CONFIG</span><h1>系统设置</h1><p>机器路径、Agent CLI 与凭据都在这里完成绑定；共享项目只保存引用 ID。</p></div></div>{notice&&<button className="notice-strip success-note" onClick={()=>setNotice('')}>{notice}</button>}{error&&<button className="notice-strip error-note" onClick={()=>setError('')}>{error}</button>}
  <div className="settings-grid"><article className="settings-card"><span className="signal-kicker">EXECUTION</span><h2>执行模式</h2><p>待我开始只收录工单；一旦授权，任务仍会自动跑完整流水线。</p><div className="segmented"><button disabled={busy} className={settings.config.execution.mode==='awaitingStart'?'selected':''} onClick={()=>void changeMode('awaitingStart')}>待我开始</button><button disabled={busy} className={settings.config.execution.mode==='automatic'?'selected':''} onClick={()=>void changeMode('automatic')}>全自动</button></div><div className="micro-facts"><span>并发 <b>{settings.config.execution.maxConcurrentTasks}</b></span><span>修复循环 <b>{settings.config.execution.maxRepairAttempts}</b></span></div></article>
  <article className="settings-card"><div className="card-title-row"><div><span className="signal-kicker">PATH BINDINGS</span><h2>机器路径</h2></div><span className="count-badge">{Object.keys(settings.config.pathBindings).length}</span></div><p>绝对路径只属于当前机器；相对路径统一相对 dataRoot。</p><div className="binding-list">{Object.entries(settings.config.pathBindings).map(([id,path])=><div key={id}><code>{id}</code><span>{path}</span></div>)}</div><div className="inline-builder"><input placeholder="binding id" value={pathId} onChange={e=>setPathId(e.target.value)}/><input placeholder="/srv/repos/product 或相对 dataRoot" value={pathValue} onChange={e=>setPathValue(e.target.value)}/><button className="primary compact" disabled={busy||!pathId||!pathValue} onClick={()=>void savePath()}>添加</button></div></article>
  <article className="settings-card span-2"><div className="card-title-row"><div><span className="signal-kicker">AGENT RUNTIMES</span><h2>Agent Profiles</h2></div><button className="ghost framed" onClick={()=>setAgent(emptyAgent())}>＋ Profile</button></div><p>Claude Code、Codex、OpenCode 各自使用独立 Adapter；Profile 只引用 executableRef，不保存机器绝对路径。</p>{settings.config.agentProfiles.length===0?<div className="mini-empty">还没有 Agent Profile</div>:<div className="profile-grid">{settings.config.agentProfiles.map(profile=><div className="profile-row" key={profile.id}><span className={`runtime-glyph runtime-${profile.runtime}`}>{profile.runtime==='claudeCode'?'C':profile.runtime==='codex'?'X':'O'}</span><div><b>{profile.id}</b><small>{profile.runtime} · {profile.model||'默认模型'}</small></div><code>{profile.executableRef}</code></div>)}</div>}</article>
  <article className="settings-card"><span className="signal-kicker">EXECUTABLES</span><h2>可执行程序</h2><p>宿主机只需把 Git/SVN/Agent CLI 放进 PATH，或在本机覆盖中配置绝对路径。</p><div className="binding-list">{Object.keys(settings.config.executableBindings).map(id=>{const binding=settings.config.executableBindings[id];return <div key={id}><code>{id}</code><span>{binding?.command?.join(' ')||'—'}</span></div>})}</div></article>
  <article className="settings-card"><div className="card-title-row"><div><span className="signal-kicker">GITLAB</span><h2>Connections</h2></div><button className="ghost framed" onClick={()=>setConnection(emptyConnection())}>＋ Connection</button></div><p>Token 仍然单独存进 Secret Vault，Connection 只保存引用。</p>{settings.config.connections.length===0?<div className="mini-empty">还没有 GitLab Connection</div>:<div className="binding-list">{settings.config.connections.map(item=><div key={item.id}><code>{item.id}</code><span>{item.baseUrl}</span></div>)}</div>}</article>
  <article className="settings-card span-2"><span className="signal-kicker">SECRETS</span><h2>凭据保险箱</h2><p>API 永远只返回 configured 状态，不回传明文。迁移机器时只需重新填写 Secret。</p><div className="secret-list">{Object.keys(settings.secrets).map(key=>{const value=settings.secrets[key];return <span key={key}><i className={value?.configured?'ready-dot':''}/>{key}</span>})}</div><div className="secret-form"><input placeholder="secret key" value={secretKey} onChange={e=>setSecretKey(e.target.value)}/><input type="password" placeholder="value" value={secretValue} onChange={e=>setSecretValue(e.target.value)}/><button className="primary compact" disabled={busy||!secretKey||!secretValue} onClick={()=>void saveSecret()}>保存 Secret</button></div></article></div>
  {agent&&<div className="modal-backdrop"><div className="config-modal"><div className="modal-head"><div><span className="signal-kicker">AGENT PROFILE</span><h2>注册 Coding Agent</h2></div><button className="icon-btn" onClick={()=>setAgent(null)} aria-label="关闭">×</button></div><div className="form-grid"><label>Profile ID<input value={agent.id} onChange={e=>setAgent({...agent,id:e.target.value})} placeholder="repair-codex"/></label><label>Runtime<select value={agent.runtime} onChange={e=>changeRuntime(e.target.value as AgentRuntime)}><option value="claudeCode">Claude Code</option><option value="codex">Codex</option><option value="opencode">OpenCode</option></select></label><label>Executable Ref<select value={agent.executableRef} onChange={e=>setAgent({...agent,executableRef:e.target.value})}>{executableIds.map(id=><option key={id}>{id}</option>)}</select></label><label>Model<input value={agent.model??''} onChange={e=>setAgent({...agent,model:e.target.value||undefined})} placeholder="留空使用 CLI 默认"/></label><label>Effort / Variant<input value={agent.effort??''} onChange={e=>setAgent({...agent,effort:e.target.value||undefined})} placeholder="high / medium / ..."/></label><label>Timeout 秒<input type="number" min={1} value={agent.timeoutSeconds??1800} onChange={e=>setAgent({...agent,timeoutSeconds:Number(e.target.value)||1800})}/></label></div><p className="form-hint">CodeFixer 会根据阶段自动收紧权限：Discovery/Review 只读，Repair 才允许写隔离工作区。</p><div className="modal-actions"><button className="ghost" onClick={()=>setAgent(null)}>取消</button><button className="primary compact" disabled={busy||!agent.id||!agent.executableRef} onClick={()=>void saveAgent()}>保存 Profile</button></div></div></div>}
  {connection&&<div className="modal-backdrop"><div className="config-modal"><div className="modal-head"><div><span className="signal-kicker">GITLAB CONNECTION</span><h2>连接 GitLab</h2></div><button className="icon-btn" onClick={()=>setConnection(null)} aria-label="关闭">×</button></div><div className="form-grid"><label>Connection ID<input value={connection.id} onChange={e=>setConnection({...connection,id:e.target.value})} placeholder="company-gitlab"/></label><label>Base URL<input value={connection.baseUrl} onChange={e=>setConnection({...connection,baseUrl:e.target.value})} placeholder="https://gitlab.example.com"/></label><label>Token Secret Ref<input value={connection.tokenSecretRef} onChange={e=>setConnection({...connection,tokenSecretRef:e.target.value})} placeholder="gitlab-token"/></label></div><p className="form-hint">这里不填写 Token 明文。保存后去下方 Secret Vault 写入同名 Secret。</p><div className="modal-actions"><button className="ghost" onClick={()=>setConnection(null)}>取消</button><button className="primary compact" disabled={busy||!connection.id||!connection.baseUrl||!connection.tokenSecretRef} onClick={()=>void saveConnection()}>保存 Connection</button></div></div></div>}
  </section>
}
