import { useEffect, useMemo, useState } from 'react'
import type { AgentProfileConfig, AgentRuntime, ConnectionConfig, ExecutionMode, SettingsResponse } from '../entities/config'
import { api } from '../lib/api'

type DraftAgent = AgentProfileConfig
type DraftConnection = ConnectionConfig
const emptyAgent = (): DraftAgent => ({ id: '', runtime: 'claudeCode', executableRef: 'claude-code-cli', timeoutSeconds: 1800 })
const emptyConnection = (): DraftConnection => ({ id: '', type: 'gitlab', baseUrl: '', tokenSecretRef: '' })

export function SettingsPage({ onModeChanged }:{ onModeChanged:(mode:ExecutionMode,etag:string)=>void }) {
  const [settings,setSettings]=useState<SettingsResponse|null>(null);const [secretKey,setSecretKey]=useState('');const [secretValue,setSecretValue]=useState('');const [pathId,setPathId]=useState('');const [pathValue,setPathValue]=useState('');const [agent,setAgent]=useState<DraftAgent|null>(null);const [connection,setConnection]=useState<DraftConnection|null>(null);const [notice,setNotice]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false)
  const load=async()=>{const next=await api.settings();setSettings(next)}
  useEffect(()=>{ load().catch(e=>setError(e instanceof Error?e.message:'加载失败')) },[])
  const executableIds=useMemo(()=>Object.keys(settings?.config.executableBindings??{}),[settings])
  if(!settings) return <section className="page-stack"><div className="page-heading"><div><h1>设置</h1><p>{error||'正在读取配置…'}</p></div></div></section>
  const put=async(config:SettingsResponse['config'],message:string)=>{setBusy(true);setError('');try{const next=await api.putSettings(config,settings.etag);setSettings(next);setNotice(message);return next}catch(e){setError(e instanceof Error?e.message:'保存失败');return null}finally{setBusy(false)}}
  const changeMode=async(mode:ExecutionMode)=>{setBusy(true);setError('');try{const r=await api.setExecutionMode(mode,settings.etag);const next={...settings,config:{...settings.config,execution:{...settings.config.execution,mode}},etag:r.etag};setSettings(next);onModeChanged(mode,r.etag);setNotice('已保存')}catch(e){setError(e instanceof Error?e.message:'模式保存失败')}finally{setBusy(false)}}
  const saveSecret=async()=>{if(!secretKey||!secretValue)return;setBusy(true);try{await api.setSecret(secretKey,secretValue);setSettings({...settings,secrets:{...settings.secrets,[secretKey]:{configured:true}}});setSecretValue('');setNotice('凭据已保存')}catch(e){setError(e instanceof Error?e.message:'凭据保存失败')}finally{setBusy(false)}}
  const savePath=async()=>{if(!pathId||!pathValue)return;const next=await put({...settings.config,pathBindings:{...settings.config.pathBindings,[pathId]:pathValue}},'本机路径已保存');if(next){setPathId('');setPathValue('')}}
  const saveAgent=async()=>{if(!agent?.id||!agent.executableRef)return;if(settings.config.agentProfiles.some(item=>item.id===agent.id)){setError(`名称已存在：${agent.id}`);return}const next=await put({...settings.config,agentProfiles:[...settings.config.agentProfiles,agent]},'AI 助手已保存');if(next)setAgent(null)}
  const saveConnection=async()=>{if(!connection?.id||!connection.baseUrl||!connection.tokenSecretRef)return;if(settings.config.connections.some(item=>item.id===connection.id)){setError(`名称已存在：${connection.id}`);return}const next=await put({...settings.config,connections:[...settings.config.connections,connection]},'GitLab 连接已保存');if(next)setConnection(null)}
  const changeRuntime=(runtime:AgentRuntime)=>setAgent(current=>current?{...current,runtime,executableRef:runtime==='claudeCode'?'claude-code-cli':runtime==='codex'?'codex-cli':'opencode-cli'}:current)
  return <section className="page-stack"><div className="page-heading"><div><h1>设置</h1><p>日常只需配置运行方式、AI 助手和凭据。</p></div></div>{notice&&<button className="notice-strip success-note" onClick={()=>setNotice('')}>{notice}</button>}{error&&<button className="notice-strip error-note" onClick={()=>setError('')}>{error}</button>}
  <div className="settings-grid simplified-settings"><article className="settings-card"><h2>运行方式</h2><p>选择新任务是自动开始，还是先等你确认。</p><div className="segmented"><button disabled={busy} className={settings.config.execution.mode==='awaitingStart'?'selected':''} onClick={()=>void changeMode('awaitingStart')}>待我开始</button><button disabled={busy} className={settings.config.execution.mode==='automatic'?'selected':''} onClick={()=>void changeMode('automatic')}>全自动</button></div></article>
  <article className="settings-card span-2"><div className="card-title-row"><div><h2>AI 助手</h2><p>为分析、修复和复核准备可用的 Coding Agent。</p></div><button className="ghost framed" onClick={()=>setAgent(emptyAgent())}>添加</button></div>{settings.config.agentProfiles.length===0?<div className="mini-empty">还没有 AI 助手</div>:<div className="profile-grid">{settings.config.agentProfiles.map(profile=><div className="profile-row" key={profile.id}><span className={`runtime-glyph runtime-${profile.runtime}`}>{profile.runtime==='claudeCode'?'C':profile.runtime==='codex'?'X':'O'}</span><div><b>{profile.id}</b><small>{profile.runtime==='claudeCode'?'Claude Code':profile.runtime==='codex'?'Codex':'OpenCode'}{profile.model?` · ${profile.model}`:''}</small></div></div>)}</div>}</article>
  <article className="settings-card"><div className="card-title-row"><div><h2>GitLab</h2><p>需要自动创建合并请求时再配置。</p></div><button className="ghost framed" onClick={()=>setConnection(emptyConnection())}>添加</button></div>{settings.config.connections.length===0?<div className="mini-empty">尚未连接</div>:<div className="binding-list">{settings.config.connections.map(item=><div key={item.id}><b>{item.id}</b><span>{item.baseUrl}</span></div>)}</div>}</article>
  <article className="settings-card span-2"><h2>凭据</h2><p>密码和 Token 只保存值，不会在界面中回显。</p><div className="secret-list">{Object.keys(settings.secrets).map(key=>{const value=settings.secrets[key];return <span key={key}><i className={value?.configured?'ready-dot':''}/>{key}</span>})}</div><div className="secret-form"><input placeholder="凭据名称" value={secretKey} onChange={e=>setSecretKey(e.target.value)}/><input type="password" placeholder="密码或 Token" value={secretValue} onChange={e=>setSecretValue(e.target.value)}/><button className="primary compact" disabled={busy||!secretKey||!secretValue} onClick={()=>void saveSecret()}>保存</button></div></article></div>
  <details className="settings-advanced"><summary>高级：本机环境</summary><div className="settings-grid advanced-grid"><article className="settings-card"><h2>路径</h2><div className="binding-list">{Object.entries(settings.config.pathBindings).map(([id,path])=><div key={id}><code>{id}</code><span>{path}</span></div>)}</div><div className="inline-builder"><input placeholder="引用名称" value={pathId} onChange={e=>setPathId(e.target.value)}/><input placeholder="本机路径" value={pathValue} onChange={e=>setPathValue(e.target.value)}/><button className="primary compact" disabled={busy||!pathId||!pathValue} onClick={()=>void savePath()}>添加</button></div></article><article className="settings-card"><h2>命令</h2><div className="binding-list">{Object.keys(settings.config.executableBindings).map(id=>{const binding=settings.config.executableBindings[id];return <div key={id}><code>{id}</code><span>{binding?.command?.join(' ')||'—'}</span></div>})}</div></article></div></details>
  {agent&&<div className="modal-backdrop"><div className="config-modal"><div className="modal-head"><div><h2>添加 AI 助手</h2></div><button className="icon-btn" onClick={()=>setAgent(null)} aria-label="关闭">×</button></div><div className="form-grid"><label>名称<input value={agent.id} onChange={e=>setAgent({...agent,id:e.target.value})} placeholder="例如：修复助手"/></label><label>工具<select value={agent.runtime} onChange={e=>changeRuntime(e.target.value as AgentRuntime)}><option value="claudeCode">Claude Code</option><option value="codex">Codex</option><option value="opencode">OpenCode</option></select></label><label>命令<select value={agent.executableRef} onChange={e=>setAgent({...agent,executableRef:e.target.value})}>{executableIds.map(id=><option key={id}>{id}</option>)}</select></label><label>模型<input value={agent.model??''} onChange={e=>setAgent({...agent,model:e.target.value||undefined})} placeholder="留空使用默认模型"/></label><label>推理强度<input value={agent.effort??''} onChange={e=>setAgent({...agent,effort:e.target.value||undefined})} placeholder="可留空"/></label><label>超时（秒）<input type="number" min={1} value={agent.timeoutSeconds??1800} onChange={e=>setAgent({...agent,timeoutSeconds:Number(e.target.value)||1800})}/></label></div><div className="modal-actions"><button className="ghost" onClick={()=>setAgent(null)}>取消</button><button className="primary compact" disabled={busy||!agent.id||!agent.executableRef} onClick={()=>void saveAgent()}>保存</button></div></div></div>}
  {connection&&<div className="modal-backdrop"><div className="config-modal"><div className="modal-head"><div><h2>连接 GitLab</h2></div><button className="icon-btn" onClick={()=>setConnection(null)} aria-label="关闭">×</button></div><div className="form-grid"><label>名称<input value={connection.id} onChange={e=>setConnection({...connection,id:e.target.value})} placeholder="例如：公司 GitLab"/></label><label>地址<input value={connection.baseUrl} onChange={e=>setConnection({...connection,baseUrl:e.target.value})} placeholder="https://gitlab.example.com"/></label><label>Token 凭据名称<input value={connection.tokenSecretRef} onChange={e=>setConnection({...connection,tokenSecretRef:e.target.value})} placeholder="gitlab-token"/></label></div><p className="form-hint">Token 的真实值在「凭据」中保存。</p><div className="modal-actions"><button className="ghost" onClick={()=>setConnection(null)}>取消</button><button className="primary compact" disabled={busy||!connection.id||!connection.baseUrl||!connection.tokenSecretRef} onClick={()=>void saveConnection()}>保存</button></div></div></div>}
  </section>
}
