import { Fragment, useEffect, useMemo, useState } from 'react'
import { StageRail } from '../design-system/StageRail'
import { STAGE_LABELS, buildRail, repairAttempts, stageDuration, stageState } from '../entities/stage'
import type { DeliveryAction, TaskRecord, TaskRun } from '../entities/task'
import { api } from '../lib/api'

const labels:Record<string,string>={awaiting_start:'待开始',queued:'等待中',running:'处理中',cancel_requested:'正在取消',completed:'已完成',failed:'失败',canceled:'已取消'}
const stageLabel=STAGE_LABELS
const state=stageState
const resultLabel=(value:string|null|undefined)=>value==='no_change'?'无需修改':value==='changed'?'已修复':'—'
const meta=stageDuration
const stageRail=buildRail
const ATTENTION=new Set(['failed','awaiting_start'])
/** 相对时间。任务列表接口不返回 stages，用 updated_at 回答「这任务还活着吗」。 */
function sinceLabel(iso:string,now:number){const ms=now-new Date(iso).getTime();if(!Number.isFinite(ms)||ms<0)return '刚刚';const min=Math.floor(ms/60000);if(min<1)return '刚刚';if(min<60)return `${min} 分前`;const hour=Math.floor(min/60);return hour<24?`${hour} 小时前`:`${Math.floor(hour/24)} 天前`}
const deliveryStatus=(value:string)=>['completed','success','succeeded'].includes(value)?'已完成':value==='failed'?'失败':value==='partial_success'?'部分完成':value==='running'?'处理中':value==='queued'||value==='pending'?'等待中':value
const deliveryType=(value:string)=>value==='patch'||value==='fallbackPatch'?'补丁':value==='gitlabPush'?'GitLab Commit':value==='githubPr'?'GitHub 拉取请求':value
const eventLabel:Record<string,string>={task_created:'任务已收录',task_started:'任务开始处理',stage_started:'阶段开始',stage_completed:'阶段完成',stage_failed:'阶段失败',task_completed:'任务已完成',task_failed:'任务失败',delivery_started:'开始交付',delivery_completed:'交付完成',delivery_failed:'交付失败'}
const failureTitle:Record<string,string>={scope_discovery_failed:'初步定位失败',discovery_no_target:'没有找到需要修改的位置',source_mismatch:'找到的位置不属于当前修改工程',workspace_policy_blocked:'文件不在允许修改的范围内',unsupported_artifact_change:'当前无法安全修改该资源',external_change_required:'需要在代码工程之外处理',verification_failed:'自动检查未通过',review_rejected:'修改结果未通过复核',delivery_failed:'远程交付失败',fallback_patch_failed:'远程交付与保底补丁均失败',workspace_prepare_failed:'修改工程准备失败'}
const failureHint:Record<string,string>={scope_discovery_failed:'打开技术详情查看定位证据；补充工单线索或定位资料后，以新任务重新运行。',discovery_no_target:'当前证据不足以确定代码位置。补充日志、符号、版本或复现信息后重新运行。',source_mismatch:'检查“定位资料”与“修改工程”是否属于同一产品版本或目录结构。',workspace_policy_blocked:'到流水线的“修改与检查规则”放行目标目录或文件类型，再创建新任务。',unsupported_artifact_change:'这通常是二进制 Prefab、专有资源或必须经编辑器修改的内容，需要人工或专用适配器处理。',external_change_required:'问题已定位，但修复点在配置、服务端、资源平台或其他未配置工作区。',verification_failed:'修改已被拦在交付前；查看失败的检查步骤与分析证据。',review_rejected:'候选修改没有通过独立复核，平台不会交付。',delivery_failed:'任务仍标记失败；若保底 Patch 成功，可从交付结果中取走补丁。',fallback_patch_failed:'检查平台数据目录的写权限和剩余空间后重试交付。',workspace_prepare_failed:'检查仓库状态、访问权限和 Git/SVN 命令后重新运行。'}
function FailureSurface({failure}:{failure:Record<string,unknown>}){const code=String(failure.code??'task_failed');const stage=String(failure.stage??'');const effects=Array.isArray(failure.side_effects)?failure.side_effects.map(String):[];return <div className="failure-surface"><div className="failure-surface-head"><span>{stageLabel[stage]??stage??'任务'}</span><code>{code}</code></div><b>{failureTitle[code]??String(failure.summary??'任务未能完成')}</b><p>{String(failure.summary??'任务未能完成')}</p>{failureHint[code]&&<small>{failureHint[code]}</small>}{effects.length>0&&<div className="failure-effects"><span>已发生的外部结果</span>{effects.map((effect,index)=><code key={`${effect}-${index}`}>{effect}</code>)}</div>}</div>}
function Delivery({action}:{action:DeliveryAction}){const result=action.result??{};const commitUrl=typeof result.commitUrl==='string'?result.commitUrl:null;const patchPath=typeof result.path==='string'?result.path:null;return <div className={`delivery-card delivery-${action.status}`}><div><b>{deliveryType(action.action_type)}</b>{action.action_type==='gitlabPush'&&action.status==='succeeded'&&<small>等待你在 GitLab Web 手动 Cherry-pick</small>}</div><span className="delivery-status">{deliveryStatus(action.status)}</span>{commitUrl&&<a className="delivery-primary-link" href={commitUrl} target="_blank" rel="noreferrer">查看 Commit ↗</a>}{patchPath&&<button className="delivery-path" title={patchPath} onClick={()=>void navigator.clipboard.writeText(patchPath)}>复制路径</button>}{action.targets?.map(t=><div className="delivery-target" key={t.id}><span>{t.target_key}</span><span>{deliveryStatus(t.status)}</span>{t.external_url?<a href={t.external_url} target="_blank" rel="noreferrer">打开</a>:null}</div>)}</div>}
function NoChangeSurface({run}:{run:TaskRun}){const evidence=(run.artifacts??[]).filter(item=>['evidence','review','verification','discovery'].some(value=>item.artifact_type.includes(value)));return <section className="no-change-surface"><div className="no-change-mark" aria-hidden="true">=</div><div><small>NO CHANGE / VERIFIED</small><h3>代码已经满足工单描述</h3><p>定位、验证与独立复核均未发现需要交付的代码差异。该任务会健康完成，并保留判断证据。</p><div className="no-change-facts"><span><b>{evidence.length}</b> 份证据</span><span><b>通过</b> 独立复核</span></div></div></section>}
function FrozenChange({run}:{run:TaskRun}){const manifest=(run.artifacts??[]).find(item=>item.artifact_type==='change_manifest');if(!manifest)return null;return <section className="frozen-change"><div><small>FROZEN CHANGE</small><b>候选修改已封存</b></div><code>{manifest.sha256.slice(0,12)}</code><span>不可变交付基线</span></section>}
function TaskConclusion({task,run}:{task:TaskRecord;run:TaskRun|undefined}){const value=run?.conclusion;
 // 没有真实结论时，失败和 no_change 都已经有专属版面在说同一件事（摘要、原因、下一步逐字相同），
 // 这里再兜一遍就是同屏复读。只有「已完成且有改动」没有别的版面兜底，才保留通用结论。
 if(!value&&(task.failure||task.result==='no_change'))return null
 const fallback={headline:'修复处理已完成',cause:'AI 已完成定位并确认问题原因。',resolution:'候选修改已经验证、复核并冻结。'};const conclusion=value??fallback;const verification=run?.verification;const passed=verification?.passed===true||verification?.status==='passed';return <section className="conclusion-sheet"><div className="conclusion-kicker">AI 结论</div><h3>{conclusion.headline}</h3><div className="conclusion-copy"><div><span>原因</span><p>{conclusion.cause}</p></div><div><span>{task.result==='no_change'?'处理':'修复方案'}</span><p>{conclusion.resolution}</p></div></div>{run&&<div className={`verification-fact ${passed?'passed':task.status==='failed'?'failed':'neutral'}`}><i/>{passed?'验证通过':task.status==='failed'?'未通过完整验证':'验证记录已保留'}</div>}</section>}
const operationLabel:Record<string,string>={add:'A',modify:'M',delete:'D',rename:'R'}
function ChangedFiles({run}:{run:TaskRun}){const files=run.change_manifest?.files??[];const[copyState,setCopyState]=useState('');const copy=async(value:string,key:string)=>{await navigator.clipboard.writeText(value);setCopyState(key);window.setTimeout(()=>setCopyState(''),1400)};if(!files.length)return null;return <section className="changed-files"><div className="changed-files-head"><div><span>修改文件</span><b>{files.length}</b></div>{files.length>1&&<button onClick={()=>void copy(files.map(item=>item.path).join('\n'),'all')}>{copyState==='all'?'已复制':'复制全部路径'}</button>}</div><div className={files.length>12?'changed-files-list scrollable':'changed-files-list'}>{files.map(item=>{const normalized=item.path.replace(/\\/g,'/');const slash=normalized.lastIndexOf('/');const directory=slash>=0?normalized.slice(0,slash+1):'';const filename=slash>=0?normalized.slice(slash+1):normalized;return <button key={`${item.operation}:${item.path}`} title={normalized} onClick={()=>void copy(normalized,normalized)}><code>{operationLabel[item.operation]??'M'}</code><span><i>{directory}</i><b>{filename}</b></span><em>{copyState===normalized?'已复制':'复制'}</em></button>})}</div></section>}
function DeliveryResult({run,onBack,onClose,onRetry}:{run:TaskRun;onBack:()=>void;onClose:()=>void;onRetry:()=>void}){const actions=run.delivery_actions??[];const failed=actions.some(item=>item.status==='failed');const commitAction=actions.find(item=>item.action_type==='gitlabPush'&&item.status==='succeeded');const commitUrl=typeof commitAction?.result?.commitUrl==='string'?commitAction.result.commitUrl:null;return <div className="modal-backdrop result-backdrop"><div className="delivery-result-modal" role="dialog" aria-modal="true" aria-label="交付结果"><div className="result-modal-head"><button className="result-back" onClick={onBack}>← 任务结论</button><button className="icon-btn" onClick={onClose} aria-label="关闭">×</button></div><header className={failed?'result-verdict failed':'result-verdict'}><small>交付结果</small><h2>{failed?'交付未完全成功':'修改已交付'}</h2><p>{commitUrl?'打开 Commit，在 GitLab Web 选择目标分支并 Cherry-pick。':failed?'已保留成功结果；远端失败时优先使用保底 Patch。':'所有配置的最终动作均已完成。'}</p>{commitUrl&&<a className="primary compact" href={commitUrl} target="_blank" rel="noreferrer">在 GitLab 查看 Commit ↗</a>}{failed&&<button className="primary compact" onClick={onRetry}>重试失败交付</button>}</header><section className="delivery-result-list"><h3>交付出口</h3>{actions.map(action=><Delivery key={action.id} action={action}/>)}</section>{run.delivery_metadata&&<details className="delivery-technical"><summary>技术信息</summary><div><span>提交日志</span><code>{run.delivery_metadata.commit_subject}</code></div>{Boolean(commitAction?.result?.commitSha)&&<div><span>Commit</span><code>{String(commitAction?.result?.commitSha)}</code></div>}{Boolean(commitAction?.result?.remoteBranch)&&<div><span>远端分支</span><code>{String(commitAction?.result?.remoteBranch)}</code></div>}</details>}<ChangedFiles run={run}/></div></div>}
/** 空账本。任务页是落地页，这一屏要回答的是「那我现在该做什么」，而不只是「这里没有东西」。 */
function LedgerEmpty({setup,synced,onNavigate}:{setup:{sources:number;projects:number}|null;synced:string;onNavigate?:(page:'projects'|'sources')=>void}){
 const blocked=setup&&(setup.sources===0||setup.projects===0)
 if(!blocked)return <div className="empty-state standby-empty"><span className="standby-signal" aria-hidden="true"><i/></span><h2>这本任务账还是空的</h2><p>界面更新于 {synced} · 工单进入后会自动出现在这里。</p></div>
 // 没有来源就永远不会有任务。此时说「一切正常，等着就行」是在骗人。
 const steps=[{done:setup.sources>0,label:'接入反馈源',hint:'Redmine 或 TAPD，平台从这里收问题',page:'sources' as const},{done:setup.projects>0,label:'建立修复通道',hint:'定位资料、修改工程与交付方式',page:'projects' as const}]
 return <div className="empty-state setup-empty"><span className="standby-signal standby-idle" aria-hidden="true"><i/></span><h2>还没有可以收问题的通路</h2><p>任务由工单自动进入。完成这两步后，符合条件的问题会自己出现在这本账上。</p>
  <ol className="setup-steps">{steps.map((step,index)=><li key={step.page} className={step.done?'step-done':''}><b>{step.done?'✓':`0${index+1}`}</b><div><span>{step.label}</span><small>{step.hint}</small></div>{!step.done&&onNavigate&&<button className="ghost framed" onClick={()=>onNavigate(step.page)}>去配置</button>}</li>)}</ol></div>
}

export function TasksPage({onNavigate}:{onNavigate?:(page:'projects'|'sources')=>void}){
 const[items,setItems]=useState<TaskRecord[]>([]);const[selected,setSelected]=useState<TaskRecord|null>(null);const[detailView,setDetailView]=useState<'conclusion'|'delivery'>('conclusion');const[error,setError]=useState('');const[filter,setFilter]=useState('all');const[syncedAt,setSyncedAt]=useState(()=>Date.now());const[now,setNow]=useState(()=>Date.now());const[setup,setSetup]=useState<{sources:number;projects:number}|null>(null)
 const load=async()=>{try{setItems((await api.tasks()).items??[]);setSyncedAt(Date.now())}catch(e){setError(e instanceof Error?e.message:'任务加载失败')}}
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),3000);return()=>clearInterval(timer)},[])
 // 空账本时才需要知道「是没配来源，还是配好了在等」。有任务就不问，省两个请求。
 useEffect(()=>{if(items.length>0){setSetup(null);return}if(setup)return;void Promise.all([api.providers(),api.projects()]).then(([p,j])=>setSetup({sources:p.items?.length??0,projects:j.items?.length??0})).catch(()=>{})},[items.length])
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[])
 useEffect(()=>{if(!selected)return;const timer=setInterval(()=>api.task(selected.id).then(setSelected).catch(()=>{}),2000);return()=>clearInterval(timer)},[selected?.id])
 useEffect(()=>{if(!selected)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape')setSelected(null)};window.addEventListener('keydown',onKey);return()=>{document.body.style.overflow=previous;window.removeEventListener('keydown',onKey)}},[selected?.id])
 const open=async(id:string)=>{try{setDetailView('conclusion');setSelected(await api.task(id))}catch(e){setError(e instanceof Error?e.message:'详情加载失败')}}
 const act=async(kind:'start'|'cancel'|'retry-delivery')=>{if(!selected)return;try{const next=kind==='start'?await api.startTask(selected.id):kind==='cancel'?await api.cancelTask(selected.id):await api.retryDelivery(selected.id);setSelected(next);await load()}catch(e){setError(e instanceof Error?e.message:'操作失败')}}
 // 异常置顶：failed / awaiting_start 是待办，其余是进度。同一张表、同一套行样式，只改顺序。
 const visible=useMemo(()=>{const all=Array.isArray(items)?items:[];const matched=filter==='all'?all:filter==='active'?all.filter(x=>['queued','running','cancel_requested'].includes(x.status)):all.filter(x=>x.status===filter);const rank=(task:TaskRecord)=>task.status==='failed'?0:task.status==='awaiting_start'?1:2;return[...matched].sort((a,b)=>rank(a)-rank(b))},[filter,items])
 const attentionCount=useMemo(()=>visible.filter(task=>ATTENTION.has(task.status)).length,[visible])
 const counts=useMemo(()=>{const all=Array.isArray(items)?items:[];return{total:all.length,running:all.filter(task=>['queued','running','cancel_requested'].includes(task.status)).length,attention:all.filter(task=>ATTENTION.has(task.status)).length}},[items])
 const run=selected?.runs?.[0]
 // 第三列：进行中看相对时间，失败看失败标题，已结束看结果。三者互斥，共用一列。
 const progress=(task:TaskRecord)=>{if(task.status==='failed')return{text:failureTitle[String((task.failure as Record<string,unknown>|null)?.code??'')]??'失败',tone:'failed'};if(task.status==='awaiting_start')return{text:'',tone:'pending'};if(['queued','running','cancel_requested'].includes(task.status))return{text:sinceLabel(task.updated_at,now),tone:'live'};return{text:resultLabel(task.result),tone:task.result??'pending'}}
 const filters=[['all','全部'],['active','处理中'],['awaiting_start','待开始'],['failed','失败'],['completed','已完成']] as const
 return <section className="page-stack tasks-page"><div className="page-heading"><div><span className="page-kicker">REPAIR RECORD</span><h1>任务</h1>{counts.total>0&&<p className="ledger-summary"><b>{counts.total}</b> 条 · <b>{counts.running}</b> 处理中 · <b>{counts.attention}</b> 需要处理</p>}</div>{counts.total>0&&<button className="ghost framed" onClick={()=>void load()}>刷新账本</button>}</div>{error&&<div className="inline-alert">{error}</div>}
 {/* 一条任务都没有时，筛选和计数都是在重复空态卡片已经说过的话 */}
 {counts.total>0&&<div className="filter-strip">{filters.map(([value,label])=><button key={value} className={filter===value?'active':''} onClick={()=>setFilter(value)}>{label}</button>)}</div>}
 {visible.length===0?counts.total>0?<div className="empty-state standby-empty"><span className="standby-signal" aria-hidden="true"><i/></span><h2>没有符合筛选的任务</h2><p>共 {counts.total} 条任务，换一个筛选条件看看。</p></div>:<LedgerEmpty setup={setup} synced={sinceLabel(new Date(syncedAt).toISOString(),now)} onNavigate={onNavigate}/>:<div className="task-table"><div className="task-table-head"><span>状态</span><span>工单与标题</span><span>进展</span><span/></div>{visible.map((task,index)=><Fragment key={task.id}>
  {attentionCount>0&&index===0&&<div className="ledger-divider" aria-hidden="true"><span>需要处理</span><i/><b>{attentionCount}</b></div>}
  {attentionCount>0&&index===attentionCount&&<div className="ledger-divider ledger-divider-rest" aria-hidden="true"><span>其余</span><i/></div>}
  <button className="task-row simple-row" data-status={task.status} onClick={()=>void open(task.id)}><span className={`task-status task-${task.status}`}>{labels[task.status]??task.status}</span><span><small>{task.provider_instance_id} #{task.external_ticket_id}</small><b>{task.title}</b></span><span className={`task-progress progress-${progress(task).tone}`}>{progress(task).text}</span><span className="row-arrow">→</span></button>
 </Fragment>)}</div>}
 {selected&&run&&detailView==='delivery'?<DeliveryResult run={run} onBack={()=>setDetailView('conclusion')} onClose={()=>setSelected(null)} onRetry={()=>void act('retry-delivery')}/>:selected&&<div className="modal-backdrop drawer-backdrop"><div className="task-drawer" role="dialog" aria-modal="true" aria-label="任务结论"><div className="modal-head"><div><span className="ticket">{selected.provider_instance_id} #{selected.external_ticket_id}</span><h2>{selected.title}</h2></div><button className="icon-btn" onClick={()=>setSelected(null)} aria-label="关闭">×</button></div><div className="fact-grid fact-grid-simple">{!selected.failure&&<div><small>状态</small><b>{labels[selected.status]}</b></div>}<div><small>结果</small><b>{resultLabel(selected.result)}</b></div><div><small>流水线</small><b>{selected.project_id??'未分配'}</b></div></div>
 {['completed','failed','canceled'].includes(selected.status)&&<TaskConclusion task={selected} run={run}/>} {selected.failure&&<FailureSurface failure={selected.failure}/>} {selected.result==='no_change'&&run&&<NoChangeSurface run={run}/>} {run&&<FrozenChange run={run}/>}
 <div className="task-actions">{selected.status==='awaiting_start'&&<button className="primary compact" onClick={()=>void act('start')}>开始处理</button>}{['queued','running'].includes(selected.status)&&<button className="danger-button" onClick={()=>void act('cancel')}>取消任务</button>}{selected.status==='failed'&&run?.artifacts?.some(a=>a.artifact_type==='change_manifest')&&<button className="primary compact retry-delivery" onClick={()=>void act('retry-delivery')}>重试交付</button>}</div>
 {run&&<><section className="drawer-section"><div className="section-head"><div><h3>处理进度</h3></div></div><StageRail stages={stageRail(run)} repairLoops={repairAttempts(run)}/></section>{(run.delivery_actions??[]).length>0&&<button className="open-delivery-result" onClick={()=>setDetailView('delivery')}><span><small>DELIVERY</small><b>查看交付结果</b></span><em>{run.change_manifest?.files.length??0} 个修改文件</em><i>→</i></button>}
 <details className="detail-disclosure"><summary>技术详情与原始阶段</summary><div className="technical-grid"><div><small>运行编号</small><code>{run.id}</code></div><div><small>任务编号</small><code>{selected.id}</code></div></div><div className="raw-stage-list">{(run.stages??[]).map(stage=><div key={stage.id}><span className={`raw-stage-state ${state(stage.status)}`}/><b>{stageLabel[stage.stage_id]??stage.stage_id}</b><code>{stage.stage_id}</code><small>第 {stage.attempt} 次 · {meta(stage)||labels[stage.status]||stage.status}</small></div>)}</div><div className="artifact-list">{(run.artifacts??[]).map(a=><div key={a.id}><span>{a.artifact_type}</span><code>{a.relative_path}</code><small>{Math.max(1,Math.round(a.size_bytes/1024))} KB · {a.sha256.slice(0,10)}</small></div>)}</div></details></>}
 <details className="detail-disclosure"><summary>执行记录</summary><div className="timeline">{selected.events?.map(event=><div className="event" key={event.id}><i/><div><b>{eventLabel[event.event_type]??event.event_type}</b><small>{event.created_at}</small></div></div>)}</div></details></div></div>}
 </section>
}
