import { useEffect, useMemo, useState } from 'react'
import { StageRail, type StageItem, type StageState } from '../design-system/StageRail'
import type { DeliveryAction, StageRun, TaskRecord, TaskRun } from '../entities/task'
import { api } from '../lib/api'

const labels:Record<string,string>={awaiting_start:'待开始',queued:'排队',running:'运行中',cancel_requested:'取消中',completed:'已完成',failed:'失败',canceled:'已取消'}
const stageLabel:Record<string,string>={prepare:'Prepare',discovery:'Discovery',no_change_verify:'No change',repair:'Repair',verify:'Verify',review:'Review',pre_delivery_check:'Stability',freeze_change:'Freeze',deliver:'Deliver'}
const state=(value:string):StageState=>value==='completed'?'done':value==='running'?'running':value==='failed'?'failed':value==='reconciling'?'reconciling':value==='canceled'?'skipped':'queued'
function meta(stage:StageRun){if(stage.started_at&&stage.finished_at){const ms=new Date(stage.finished_at).getTime()-new Date(stage.started_at).getTime();return ms<1000?`${ms}ms`:`${(ms/1000).toFixed(1)}s`}return stage.status==='running'?'live':stage.status}
function stageRail(run:TaskRun):StageItem[]{const order=['prepare','discovery','no_change_verify','repair','verify','review','pre_delivery_check','freeze_change','deliver'];const latest=new Map<string,StageRun>();for(const item of run.stages??[])latest.set(item.stage_id,item);return order.filter(id=>latest.has(id)||!['no_change_verify','pre_delivery_check','freeze_change'].includes(id)).map(id=>{const item=latest.get(id);return{label:stageLabel[id]??id,meta:item?meta(item):'queued',state:item?state(item.status):'queued'}})}
function Delivery({action}:{action:DeliveryAction}){return <div className={`delivery-card delivery-${action.status}`}><div><span className="signal-kicker">{action.action_type}</span><b>{action.action_id}</b></div><span className="delivery-status">{action.status}</span>{action.targets?.map(t=><div className="delivery-target" key={t.id}><code>{t.target_key}</code><span>{t.status}</span>{t.external_url?<a href={t.external_url} target="_blank" rel="noreferrer">打开 ↗</a>:null}</div>)}</div>}

export function TasksPage(){
 const[items,setItems]=useState<TaskRecord[]>([]);const[selected,setSelected]=useState<TaskRecord|null>(null);const[error,setError]=useState('');const[filter,setFilter]=useState('all')
 const load=async()=>{try{setItems((await api.tasks()).items)}catch(e){setError(e instanceof Error?e.message:'任务加载失败')}}
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),3000);return()=>clearInterval(timer)},[])
 useEffect(()=>{if(!selected)return;const timer=setInterval(()=>api.task(selected.id).then(setSelected).catch(()=>{}),2000);return()=>clearInterval(timer)},[selected?.id])
 const open=async(id:string)=>{try{setSelected(await api.task(id))}catch(e){setError(e instanceof Error?e.message:'详情加载失败')}}
 const act=async(kind:'start'|'cancel'|'retry-delivery')=>{if(!selected)return;try{const next=kind==='start'?await api.startTask(selected.id):kind==='cancel'?await api.cancelTask(selected.id):await api.retryDelivery(selected.id);setSelected(next);await load()}catch(e){setError(e instanceof Error?e.message:'操作失败')}}
 const visible=useMemo(()=>filter==='all'?items:items.filter(x=>x.status===filter),[filter,items]);const run=selected?.runs?.[0]
 return <section className="page-stack"><div className="page-heading"><div><span className="eyebrow">TASK FACTS</span><h1>任务</h1><p>Task 是 Bug 的长期身份；Run、Stage、Artifact 与外部交付都是可恢复事实。</p></div><button className="ghost framed" onClick={()=>void load()}>刷新 ↻</button></div>{error&&<div className="inline-alert">{error}</div>}
 <div className="filter-strip">{['all','running','queued','awaiting_start','failed','completed','canceled'].map(x=><button key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x==='all'?'全部':labels[x]??x}<em>{x==='all'?items.length:items.filter(i=>i.status===x).length}</em></button>)}</div>
 {visible.length===0?<div className="empty-state"><span className="empty-mark">≡</span><h2>这里还没有任务</h2><p>配置工单来源和 Project 路由后，新 Bug 会自动出现；待我开始模式只收录，不调用 Agent。</p></div>:<div className="task-table">{visible.map(task=><button key={task.id} className="task-row" onClick={()=>void open(task.id)}><span className={`task-status task-${task.status}`}>{labels[task.status]??task.status}</span><span><small>{task.provider_instance_id} · #{task.external_ticket_id}</small><b>{task.title}</b></span><code>{task.project_id??'UNROUTED'}</code><span className="result-chip">{task.result==='no_change'?'NO CHANGE':task.result==='changed'?'CHANGED':''}</span><span className="row-arrow">→</span></button>)}</div>}
 {selected&&<div className="modal-backdrop drawer-backdrop"><div className="task-drawer" role="dialog" aria-modal="true"><div className="modal-head"><div><span className="ticket">{selected.provider_instance_id} #{selected.external_ticket_id}</span><h2>{selected.title}</h2></div><button className="icon-btn" onClick={()=>setSelected(null)} aria-label="关闭">×</button></div><div className="fact-grid"><div><small>状态</small><b>{labels[selected.status]}</b></div><div><small>结果</small><b>{selected.result??'—'}</b></div><div><small>项目</small><b>{selected.project_id??'未路由'}</b></div><div><small>当前 Run</small><code>{selected.current_run_id?.slice(0,14)||'—'}</code></div></div>
 {selected.failure&&<div className="failure-surface"><span className="failure-code">{String(selected.failure.code??'FAILED')}</span><b>{String(selected.failure.summary??'任务失败')}</b><p>{String(selected.failure.stage??'')}</p></div>}
 {selected.status==='awaiting_start'&&<button className="primary compact" onClick={()=>void act('start')}>开始完整流程</button>}{['queued','running'].includes(selected.status)&&<button className="danger-button" onClick={()=>void act('cancel')}>取消任务</button>}{selected.status==='failed'&&run?.artifacts?.some(a=>a.artifact_type==='change_manifest')&&<button className="primary compact retry-delivery" onClick={()=>void act('retry-delivery')}>仅重试交付 · 不重跑 Agent</button>}
 {run&&<><section className="drawer-section"><div className="section-head"><div><span className="signal-kicker">STAGE SIGNAL</span><h3>当前 Run</h3></div><code>{run.id}</code></div><StageRail stages={stageRail(run)}/></section><section className="drawer-split"><div><span className="signal-kicker">ARTIFACTS</span><div className="artifact-list">{(run.artifacts??[]).map(a=><div key={a.id}><span>{a.artifact_type}</span><code>{a.relative_path}</code><small>{Math.max(1,Math.round(a.size_bytes/1024))} KB · {a.sha256.slice(0,10)}</small></div>)}</div></div><div><span className="signal-kicker">DELIVERY</span><div className="delivery-list">{(run.delivery_actions??[]).length?(run.delivery_actions??[]).map(a=><Delivery key={a.id} action={a}/>):<p className="muted-copy">尚未产生外部交付。</p>}</div></div></section></>}
 <section className="drawer-section"><span className="signal-kicker">EVENT TIMELINE</span><div className="timeline">{selected.events?.map(event=><div className="event" key={event.id}><i/><div><b>{event.event_type}</b><small>{event.created_at}</small></div></div>)}</div></section></div></div>}
 </section>
}
